### ISSUE TITLE
Jiotv runtime error

### ISSUE THREAD

**Issue by imluckie** [botallen/repository.botallen#102]
No channel is getting played. All I can see a popup showing **Runtime error**. Also, having a high speed internet, ColorsTV is always lagging the speed and keeps on buffering.

**Comment by iMro0t** [comment]
Please follow the issue template so I can get the basic information.

The runtime error used to cause in older version so make sure you are on latest v2.0.14.
If you still facing the issue then please provide a debug log

**Comment by Manish081290** [comment]
Please solve this problem all channels not working

**Comment by anishsane** [comment]
This is the error seen while playing any channel:

```
ERROR: [JioTV.support] play() got an unexpected keyword argument 'id'
     Traceback (most recent call last):
       File "/home/pi/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 325, in run_callback
         results = route.function(parent_ins, *arg_params, **self.callback_params)
       File "/home/pi/.kodi/addons/plugin.video.jiotv/resources/lib/utils.py", line 35, in login_wrapper
         return func(*args, **kwargs)
     TypeError: play() got an unexpected keyword argument 'id'
```

I also tried to logout+login, just in case, there was a stale login token.
