### ISSUE TITLE
[ Jio TV] it asks for password but jio requires OTP

### ISSUE THREAD

**Issue by arrow00009** [botallen/repository.botallen#103]
**Your Environment**
- Add-on name: [e.g. Jiotv]
- Add-on version: [e.g. 2.0.0]
- Operating system version/name: [e.g. Windows 10, LibreElec 9.0, etc...]A
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Debug log**

The debug log can be found from this link:

**Comment by codito** [comment]
Jio has made it notoriously hard to signup with email/password. Here's what worked for me:

* Download the JioTV app
* First screen shows option to sign in - **choose Jio Id** option here
* You should see an option to create new id or recover password etc.
* Sign up with your email address associated with Jio number (you can add email in My Jio app or online jio portal first)
* Now use the email/password in Kodi

Hope this saves some time.

**Comment by iMro0t** [comment]
Thanks, @codito for an explanation. Closing this issue since it'll be not implemented in the future as well because OTP authentication is temporary and you have to do it every 5 days. That's why it uses the password to do the job for you.

**Comment by xts-velkumars** [comment]
> Jio has made it notoriously hard to signup with email/password. Here's what worked for me:
> 
> * Download the JioTV app
> * First screen shows option to sign in - **choose Jio Id** option here
> * You should see an option to create new id or recover password etc.
> * Sign up with your email address associated with Jio number (you can add email in My Jio app or online jio portal first)
> * Now use the email/password in Kodi
> 
> Hope this saves some time.

If my understanding is correct, for getting JIO Id and password JIO Fiber is required ?

**Comment by codito** [comment]
@xts-velkumars no, just jio sim works (I don't have jio fiber). Try downloading the JioTV app on your phone and follow the rest of the steps.

**Comment by xts-velkumars** [comment]
> @xts-velkumars no, just jio sim works (I don't have jio fiber). Try downloading the JioTV app on your phone and follow the rest of the steps.

Got, it. Thank you. Its working now
