### ISSUE TITLE
Jio TV stopped working completely

### ISSUE THREAD

**Issue by devil47sid** [botallen/repository.botallen#104]
**Your Environment*
- Add-on name: Jiotv
- Add-on version: 2.0.15
- Operating system version/name: Android 9.0

**Describe the bug**
Unable to play any channel without any error message.

**To Reproduce**
Play any channel

**Expected behavior**
The channels should play as before

**Comment by iMro0t** [comment]
Re-login from add-on settings and try playing the channel again.

**Comment by Craja753** [comment]
Re-login also not working showing "ConnError" "Name or Service not known"

**Comment by devil47sid** [comment]
It's resolved after 2 days. Not sure if Jio services were down or something else
