### ISSUE TITLE
Free membership is not working!!

### ISSUE THREAD

**Issue by sathishdsr** [botallen/repository.botallen#106]
**Your Environment**
- Add-on name: Tivimate
- Add-on version: [e.g. 2.0.0]
- Operating system version/name: Android 9.0

**Describe the bug**
Free membership is not working anymore. Saying "you need VIP membership to stream this video". I am using one playlist with 230 channels.

**Comment by iMro0t** [comment]
Totally irrelevant. This repository only covers Kodi add-ons. Join discord for more on this
