### ISSUE TITLE
Kodi 19 Matrix Support

### ISSUE THREAD

**Issue by mahendranm** [botallen/repository.botallen#107]
**Describe the bug**
Unable to use this add-on since it doesn't show and video add-on

**To Reproduce**
1. Download the latest app from android
2. Add this repository

**Expected behavior**
Video add-on should be shown

**Screenshots**
![Screenshot_20210117-214034](https://user-images.githubusercontent.com/9550822/104849115-17e17d80-590e-11eb-90ab-6eed54b9e84a.jpg)

**Debug log**
The debug log can be found from this link:
https://drive.google.com/file/d/1etqTreBro0WKpPkFtdQKcKDq0X09vLTG/view?usp=drivesdk

**Comment by iMro0t** [comment]
Kodi 19.0 (Matrix) is not supported yet. Keeping this issue open for tracking Matrix support
