### ISSUE TITLE
Migration from Python 2 to 3 introduced instability for this plugin

### ISSUE THREAD

**Issue by MayurPrajapati** [botallen/repository.botallen#114]
**Android TV**
- Add-on name: Jiotv
- Add-on version: 2.0.0
- Kodi version: Kodi 19
- Operating system version/name: Android TV Pie

**Describe the bug**
Kodi v19 introduced migration from Python 2 to 3. Which is why this plugin is not working.

**To Reproduce**
Plugin shown as outdated.

**Expected behavior**
It should show all the available shows & options.

**Comment by iMro0t** [comment]
Duplicate of #107
