### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by dilip1232** [botallen/repository.botallen#115]
**Your Environment**
- Add-on name: hotstar
- Add-on version: 31.2
- Kodi version: kodi 18.6
- Operating system version/name: Osmc

**Describe the bug**
Unable to login. The screen with code comes and even after entering code in browser and successfully login in. The login screen in tv times out. Nothing happens.

**To Reproduce**

**Expected behavior**
The screen should not time out. Login success message should display.

**Screenshots**

**Additional context**

**Debug log**

The debug log can be found from this link:

**Comment by iMro0t** [comment]
willforde/script.module.codequick#45

**Comment by dilip1232** [comment]
Thank you. Updated codequick.
Working fine now.
