### ISSUE TITLE
Catch Up Episode not working

### ISSUE THREAD

**Issue by saumilwaghela** [botallen/repository.botallen#121]
**Your Environment**
- Add-on name: JioTV
- Add-on version: 2.0.0 (latest)
- Kodi version: kodi 18.3
- Operating system version/name: MXQ PRO 4k 5G Android TV Box

**Describe the bug**
Not able to catch up channel's old episode
**To Reproduce**
1. Select Channel say Sony TV HD
2. Open Guide where all old episode list appears
3. press ok button on any old episode
4. Popup opens click on switch ..it doesnot open old episode

**Expected behavior**
Catch up of channel should happen

**Comment by saumilwaghela** [comment]
Not a Bug got it

**Comment by iMro0t** [comment]
FYI: Latest version of Jiotv add-on is 2.1.3 but it requires Kodi 19 so I would suggest to use the latest one if possible
