### ISSUE TITLE
Error while playing hotstar video 'HTTPERROR' object has no attribute 'code'

### ISSUE THREAD

**Issue by Yurila123** [botallen/repository.botallen#122]

**Comment by iMro0t** [comment]
Describe your issue in detail. How to reproduce your issue with steps?

**Comment by Yurila123** [comment]
![16172271990117864612443329113137](https://user-images.githubusercontent.com/81669265/113215609-a0fc2580-926a-11eb-981a-8bd80b179b61.jpg)

**Comment by iMro0t** [comment]
@Yurila123 I can see this is not the latest version of the add-on. Please install the latest version of Disney+ Hotstar v1.0.1 add-on from repository v2.0.0

**Comment by Yurila123** [comment]
I have the latest version but still shows same issue

**Comment by twoEyedPotat** [comment]
@Yurila123 Hi I also faced similar issue and logging into hotstar again solved me. Although, I am facing frequent logouts from hotstar when not used. Did you face similar issue ?

**Comment by NikitPulekar** [comment]
I am also facing same issue in pi 4.

**Comment by arkabhowmick** [comment]
Same issue in pi 3. Hotstar is getting logged out

**Comment by Justintiger9** [comment]
Same issue here. Installed from https://kodi.botallen.com according to your instructions. Running on Leia, and the version I got from the repo is 0.0.31.2. Seems like the version of Hotstar in the repo might be outdated. P.S. Device I'm using is a Pi 4, logging in from Malaysia. Just want to say thanks for your work on this add-on, and I hope this issue might be resolved soon.

**Comment by radiantshaw** [comment]
I'm getting the same error as well on the latest version. Let me know if you need more info.

**Comment by radiantshaw** [comment]
To add more context. The issue seems to happen when you're trying to click on a video to login. It should display a login popup, but instead, the error is shown.

Hopefully this will provide more details to resolve it.

**Comment by radiantshaw** [comment]
## Possible solution

I was able to solve it by logging it from the add-on "Configure" section.

- There's a separate "Configure" option on the same screen as the "Uninstall" option (do check how to go to the "Uninstall" screen since it's different based on the skin you're using)
- Selecting the "Configure" option takes you to the "Login" and "Logout" options screen
- Select "Login" and follow the steps
- Now play any video and it should work

This would mean that even if you want to watch free videos, you need to log in.

**Comment by iMro0t** [comment]
@radiantshaw which version you are using? Are you using v2 repo for matrix or older version? 
I checked it and this issue was fixed in add-on v2.0.0.

**Comment by radiantshaw** [comment]
@iMro0t I am using the V2 repo, but for some reason the Hotstar addon is not the latest.

**Comment by iMro0t** [comment]
@radiantshaw Try reinstalling the add-on it should be on the latest version. Closing this issue as of now because it's not reproducible. Reopen if still facing the same issue
