### ISSUE TITLE
Stream quality is fixed. How to increase Stream quality in Jio TV Botallen 2.0.0 addon

### ISSUE THREAD

**Issue by kartikc123** [botallen/repository.botallen#123]
How to increase stream quality in Jio TV Botallen 2.0.0 addon
![Capture](https://user-images.githubusercontent.com/81894475/113499001-cb323980-952f-11eb-97ae-11fff4c6b7c2.JPG)

**Comment by iMro0t** [comment]
You have to enable it from settings.

Goto My-addons > VideoPlayer InputStream > Inputstream Adaptive and open settings. In settings change Stream Selection from Auto to Manual video
And then you can switch between multiple stream quality from the OSD menu

Closing this issue it's not related to add-on.
