### ISSUE TITLE
Unable to Update Disney+ Hotstar

### ISSUE THREAD

**Issue by kedarbhise** [botallen/repository.botallen#127]
**Your Environment**
- Add-on name: Disney+ Hotstar
- Add-on version: 0.0.31.2

- Operating system version/name: OSMC 2020.11-1 on Raspberry Pi 3B+, with Kodi 18.9

**Describe the bug**
Unable to update Disney+ Hotstar beyond 0.0.31.2.
Due to this, unable to get the fix for #88 

**To Reproduce**
1. Right click on Botallen Repository and choose Update.
2. Even after update shows version 1.0.0
3. Right click on Disney+ Hotstar Add on and choose Update
4. Even after update shows version 0.0.31.2
 
**Expected behavior**
Both the repository and add on should update to latest versions.

**Comment by kedarbhise** [comment]
I was able to update the relevant OSMC packages using the instructions here:
https://discourse.osmc.tv/t/testing-kodi-v19-builds-for-raspberry-pi-2-3-4/89152

Now the Kodi version is 19 - Matrix.

This allowed me to update the Repository to 2.0.0 and the Add-on to 1.0.1.

However, even after updating the Add-on, I find that #88 still persists.

**Comment by iMro0t** [comment]
Fixed in https://github.com/botallen/plugin.video.botallen.hotstar/commit/995b1903f8f2a317bac1270bc61371f695805dbb
