### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by Vyomax** [botallen/repository.botallen#129]
The addon suddenly stopped working on my raspberry Pi 3. when tried to reinstall, it failed to install again.

**Comment by iMro0t** [comment]
If you are using Kodi 19 Matrix then use repository v2.0.0.

**Comment by dgbkn** [comment]
Today it stopped working please fix it sir

**Comment by dgbkn** [comment]
I am using 2.0

**Comment by prvndan** [comment]
Its asking for login

**Comment by Vyomax** [comment]
Yes login is required,, you need to use your Jio login credentials for that.

**Comment by Vyomax** [comment]
> If you are using Kodi 19 Matrix then use repository v2.0.0.

I am using the v2.0.0, but can not install it. first the existing installation stopped working and then re-install is not possible.

**Comment by dgbkn** [comment]
ok now its working sir thanks

**Comment by iMro0t** [comment]
Re-open if still facing the issue.
