### ISSUE TITLE
Jiotv full hd quality streams

### ISSUE THREAD

**Issue by popfan161** [botallen/repository.botallen#132]
## Feature request
For Add-on ... Jiotv
I'm submitting a proposal to ...
  - [ ] change an existing feature - In jiotv addon, quality of the channels are not at par with what jio actually provides. Can you give the option to stream the hd channels at 1080p with atleast 1.5mbps bitrate (similar to what jiotv actually offers). For some live channels like sony channels, I can see the source is sony liv, but they are offering highest quality at about 4mbps for almost all the channels in sony liv. Can you add that stream quality too.

#### Is your feature request related to a problem? Please describe.
No, this is not a problem; but since native jiotv offers content at better quality, so am expecting your app to do the same for better viewing experience.

#### Describe the solution you'd like
Atleast to have the highest quality stream as provided by native jiotv app. For e.g. for hd channels, juotv offers 1080p streams at 1.5mbps (still its not as good as compared to what apps like sony liv offers)

#### Describe alternatives you've considered
For sony channels, sony liv is a much better source - for non hd channels also it provides stream at about 4mbps which is much better than airteltv or jiotv streams for the same channels

#### Development tips
I am not a delevoper so skipping here

#### Additional context
Nothing additional

**Comment by iMro0t** [comment]
> Can you give the option to stream the hd channels at 1080p with atleast 1.5mbps bitrate (similar to what jiotv actually offers).

Jiotv doesn't provide 1080p streams. Sonyliv channels which has sonyliv watermark are actually from Jiotv's server which is not served in 1080p from the source itself.

**Comment by popfan161** [comment]
oh ok bro... i was referring to some unofficial apps which claim to stream jio streams (not mentioning names here) and have video stream at 1080p .. i understand you are streaming whichever is offered by jioserver..so it's all good. But like others have requested to have streams from sources like tata sky etc, would have a generic request if still you can include sources where we can get better quality

**Comment by vigneshboolog** [comment]
i am also facing this problem of low streaming quality. Is there any way i can increase it?

**Comment by spknair** [comment]
is jio server streaming channels at 480p?

**Comment by sunilroyy007** [comment]
> oh ok bro... i was referring to some unofficial apps which claim to stream jio streams (not mentioning names here) and have video stream at 1080p .. i understand you are streaming whichever is offered by jioserver..so it's all good. But like others have requested to have streams from sources like tata sky etc, would have a generic request if still you can include sources where we can get better quality

What are the other apps i want to stream in good quality. Mention those names

**Comment by Harsh3101** [comment]
Play this momix app in kodi 
Plz reply
![Screenshot_20220114-143436_MOMIX_BY_AMOUR](https://user-images.githubusercontent.com/97713646/149488881-3fe190e7-a42d-4451-94b7-64f966dfd2dc.png)

**Comment by iMro0t** [comment]
> Play this momix app in kodi Plz reply

You can only launch android app from Kodi. You can't play android app in Kodi.

**Comment by iamsom7** [comment]
> ## Feature request
> For Add-on ... Jiotv I'm submitting a proposal to ...
> 
> * [ ]  change an existing feature - In jiotv addon, quality of the channels are not at par with what jio actually provides. Can you give the option to stream the hd channels at 1080p with atleast 1.5mbps bitrate (similar to what jiotv actually offers). For some live channels like sony channels, I can see the source is sony liv, but they are offering highest quality at about 4mbps for almost all the channels in sony liv. Can you add that stream quality too.
> 
> #### Is your feature request related to a problem? Please describe.
> No, this is not a problem; but since native jiotv offers content at better quality, so am expecting your app to do the same for better viewing experience.
> 
> #### Describe the solution you'd like
> Atleast to have the highest quality stream as provided by native jiotv app. For e.g. for hd channels, juotv offers 1080p streams at 1.5mbps (still its not as good as compared to what apps like sony liv offers)
> 
> #### Describe alternatives you've considered
> For sony channels, sony liv is a much better source - for non hd channels also it provides stream at about 4mbps which is much better than airteltv or jiotv streams for the same channels
> 
> #### Development tips
> I am not a delevoper so skipping here
> 
> #### Additional context
> Nothing additional

jio have streams in 8mbps too
