### ISSUE TITLE
Star Channels not streaming

### ISSUE THREAD

**Issue by codejack11** [botallen/repository.botallen#134]
**Your Environment**
- Add-on name: Jiotv
- Add-on version: 2.0.14
- Kodi version: Kodi 18.9
- Operating system version/name: OSMC

**Describe the bug**
Whenever I click on any Star network channel e.g. Star Plus, Star Gold, it does nothing. After clicking channel, loader is activates for sometime and nothing happen. All other channels are working great. 

Can you please suggest me any method to overcome this.

**Comment by iMro0t** [comment]
You need to use Kodi 19 and the latest add-ons from repository v2
