### ISSUE TITLE
Playback failed on jioTV

### ISSUE THREAD

**Issue by dgbkn** [botallen/repository.botallen#135]
Environment
- Add-on name: Jiotv
- Add-on version: 2.0.0
- Kodi version: e.g. Kodi 19
- Operating system version/name : LibreElec

**Comment by dgbkn** [comment]
It was working after logging in again

**Comment by jaspreet342141** [comment]
I have the same problem I have to re-login every 15 or 30 days later
did that happen to you just once or is it still happening?? @dgbkn
