### ISSUE TITLE
Error: Kodi not connecting with the repository.

### ISSUE THREAD

**Issue by sureshparekh** [botallen/repository.botallen#136]
**Your Environment**
- Add-on name: [e.g. Jiotv]
- Add-on version: [e.g. 2.0.0]
- Kodi version: [e.g. Kodi 19]
- Operating system version/name: Android TV 10
**Describe the bug**
After completing the steps of adding the source and installing the zip file, at the time of opening the repository, to shows:  Kodi not connecting with the repository. 

**To Reproduce**

**Expected behaviour**
Kodi application should be connected with the repository at the time of installation.

**Comment by iMro0t** [comment]
I can't reproduce this. Since it's an old issue please re-open if you still facing the same error.
