### ISSUE TITLE
Sync watched status with Hotstar feature

### ISSUE THREAD

**Issue by weyzax** [botallen/repository.botallen#138]
## Feature request
# For Add-on: Disney+ Hotstar
It would be amazing to have an option in the Hotstar add-on settings that allows the user to toggle the synchronization of watch status with the official server's library.
  - [x] new feature
  - [ ] change an existing feature

#### Additional context
Similar implementations can be found in the Disney+ and Netflix add-ons.

![nGyh8f1qj3](https://user-images.githubusercontent.com/66939327/119216903-1a3e2900-baf4-11eb-9443-7a68f3f16db1.png)

![eHSubFupTb](https://user-images.githubusercontent.com/66939327/119216910-1f9b7380-baf4-11eb-9086-acc7a14aa87b.png)

https://github.com/CastagnaIT/plugin.video.netflix/pull/385

https://github.com/CastagnaIT/plugin.video.netflix/pull/894

**Comment by iMro0t** [comment]
This is still only partially supported. It only shows resumable content which you previously watched on Hotstar. It's not updating watching progress in Hotstar. It's quite complicated to implement and Kodi doesn't give any straightforward solution to implement this kind of thing. Other addons use proxy to achieve this
