### ISSUE TITLE
JioTV with iptv-merger 

### ISSUE THREAD

**Issue by SJ50** [botallen/repository.botallen#14]
How do I make jioTV with iptv-merger addon (repo - http://k.slyguy.xyz ) ?
When I merger playlist from resources/extra/jiotv.m3u with iptv-merger any jio channel does not work.

**Comment by botallen** [comment]
IPTV-merger is not supported by JioTV. You can still merge with m3u file and in order to play channels jiotv add-on must be installed

**Comment by SJ50** [comment]
So If I merge manually jio channel will work?

**Comment by botallen** [comment]
Yes. M3u is having local url that is responsible to play channels so you must need jiotv add-on working in background. I suggest you to merge other channels in jiotv.m3u
