### ISSUE TITLE
Star Live Channels stopped working

### ISSUE THREAD

**Issue by nikhilk0** [botallen/repository.botallen#142]
**Environment**
- Add-on name: Jiotv, Disney+ Hotstar
- Add-on version: Latest available for both
- Kodi version: Kodi 19
- Operating system version/name: Windows 10, Android

**Describe the bug**
Star live channels now ask for login if not logged in. And after login throw subscription error.

**To Reproduce**
Play any of the star live channels either from jiotv or from hotstar addon.

**Expected behavior**
Play the channel which were working fine till last week.

**Debug log snippet**
[star live log.txt](https://github.com/botallen/repository.botallen/files/6604372/star.live.log.txt)

**Comment by paritoshec** [comment]
Is this fixed ?

**Comment by siddhusubbu** [comment]
Same here, subscription error. Not fixed yet.

**Comment by viveksuraiya** [comment]
Please advise when fixed. I have a VIP subscription through JioFiber.
