### ISSUE TITLE
Add Support for ODIA Channels

### ISSUE THREAD

**Issue by abprime** [botallen/repository.botallen#145]
**Your Environment**
- Add-on name: [Jiotv]
- Add-on version: [2.0.0]
- Kodi version: [Kodi 19]
- Operating system version/name: [FireTV]

**Describe the bug**
Odia Channels doesn't appear in the languages, whereas it is available in JioTV.

**To Reproduce**
1. Go to 'Languages'
2. Cannot find 'Odia' in channel list.

**Expected behavior**
Odia Channel Should appear in the list of languages.

**Comment by theplaygod97** [comment]
Same effect the Odia Section ,All other languages are added , Please add it
