### ISSUE TITLE
for some reason, the addon stops working after a month and I have to sign out and sign in again

### ISSUE THREAD

**Issue by jaspreet342141** [botallen/repository.botallen#148]
**Your Environment**
- Add-on name: [e.g. Jiotv]
- Add-on version: [e.g. 2.0.0]
- Kodi version: [e.g. Kodi 19]
- Operating system version/name: [e.g.Android mobile version.]

**Describe the bug**
whenever I install jio TV addon after a month I start getting a video playback error and when I logout and login with my jio account it gets fixed 
I know it's not a big issue but I didn't knew that logging out and login in would fix it for the last three months I would have to uninstall the addon and reinstall it I just found out that it gets fixed if you logout and login
could it be that because I have been using the same jio account on two or three kodi
and I also didn't install it the right way I had it installed and then I used to the backup tool to install it to my other TV which I am currently using it on but I have tried uninstalling and reinstalling I also got the after that
**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Debug log**

The debug log can be found from this link:

**Comment by hs16042016** [comment]
SAME TO SAME ISSUE I AM ALSO FACING
