### ISSUE TITLE
Aaj Tak not working for a long time

### ISSUE THREAD

**Issue by jaspreet342141** [botallen/repository.botallen#149]
**Your Environment**
- Add-on name: [e.g. Jiotv]
- Add-on version: [e.g. 2.0.0]
- Kodi version: [e.g. Kodi 19]
- Operating system version/name: [e.g. Windows 10, LibreElec 9.0, etc...]

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Debug log**

The debug log can be found from this link:

**Comment by hs16042016** [comment]
SAME ISSUE I AM ALSO FACING
