### ISSUE TITLE
streaming quality

### ISSUE THREAD

**Issue by vigneshboolog** [botallen/repository.botallen#151]
hi, the streaming quality in jiotv in set to very low. Is there any way i can change the streaming quality to HD

**Comment by mkp95** [comment]
I have the exact opposite problem. It's always more than enough for me. I would like to get a multi quality option if possible.

**Comment by spknair** [comment]
> hi, the streaming quality in jiotv in set to very low. Is there any way i can change the streaming quality to HD

I am also getting stream at 480p only 😥

**Comment by iMro0t** [comment]
Duplicate of #132
