### ISSUE TITLE
You do not have a valid subscription to watch this content. Error for Hotstar

### ISSUE THREAD

**Issue by gbhangale416** [botallen/repository.botallen#153]
**Your Environment**
- Add-on name:  Hotstar
- Kodi version: [e.g. Kodi 19]
- Operating system version/name: Android Tv

**Describe the bug**
The live tv shows an error "subscription error".

**To Reproduce**
1. Go to tv in kodi
2. Open any star channel
3. See error "you do not have a valid subscription to watch this content" even after logging in to Hotstar with valid login with premium subscription.

**Screenshots**
If applicable, add screenshots to help explain your problem
![IMG20210716072527](https://user-images.githubusercontent.com/29910202/125880397-6b9d25ad-6554-43b1-819c-607f49b5c3d1.jpg)

**Comment by Arnabgit** [comment]
Same error is shown though I have a premium subscription

**Comment by gbhangale416** [comment]
> Same error is shown though I have a premium subscription

I also have premium subscription but still getting error.

**Comment by viveksuraiya** [comment]
I'm getting the same error!

**Comment by arsudarsan** [comment]
Same issue for me as well

**Comment by drkathirpi** [comment]
same issue for me as well

**Comment by ousudrs** [comment]
same issue for me as well

**Comment by fuzzylogic777** [comment]
I get the same error on Kodi Matrix 19.3. Is there any latest Kodi addon for this issue?
