### ISSUE TITLE
Dont have JIO ID password and can't reset it anymore. Jio has completely shifted to OTP Based login.

### ISSUE THREAD

**Issue by jaipaljadeja** [botallen/repository.botallen#154]
I tried to reset the password from the forgot password option in JIO TV app itself. It gives me an error "Jio id doesn't seem to be active please activate you account" so it asks me to signup when I do signup it mails me an account verification link which always redirects to the jio login page and doesn't actually activates the account. I tried several methods but none of them work anymore. 

Is there any way to get around this situation and log in to the jio tv addon?

**Comment by duoadmin** [comment]
I recently forgot my password and set a new one

**Comment by sahilbest999** [comment]
I'm having same issue

**Comment by jaipaljadeja** [comment]
> I recently forgot my password and set a new one

if you already had a password reset once before it will work but suppose you use a new jio number which never had a password reset, it wont work.

**Comment by sahilbest999** [comment]
https://signup.jio.com/

Visit this URL and Go to Forgot Password, then you should be able to change the password

**Comment by jaspreet342141** [comment]
download jio tv and go to sign in and sign in with ID now create a new user if you don't have account already when you do everything you will get a verification link on your email click on that link and then you will be redirected to jio login page click on mobile and then click on login you need to login with OTP in there. and your account will be active  first I thought it's not working but then it worked I made my new account after seeing your post it still working @jaipaljadeja

**Comment by jaipaljadeja** [comment]
it worked! thank you so much @jaspreet342141 appreciate the help.
