### ISSUE TITLE
can we use one jio account on multiple devices

### ISSUE THREAD

**Issue by jaspreet342141** [botallen/repository.botallen#155]
**Your Environment**
- Add-on name: [e.g. Jiotv]
- Add-on version: [e.g. 2.0.0]
- Kodi version: [e.g. Kodi 19]
- Operating system version/name: [e.g. Windows 10, LibreElec 9.0, etc...]

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Debug log**

The debug log can be found from this link:

**Comment by iMro0t** [comment]
Yes. But it has some limits obviously. I am not sure how many devices but for general use, it'll be fine for 2-3 devices.
