### ISSUE TITLE
Query: Live Channels App

### ISSUE THREAD

**Issue by impurnendu** [botallen/repository.botallen#156]
Hi,
There is an app called "Live Channels" on Android TV. But how can I integrate JioTV channels on that app??? Is there any way to extract m3u8 file from your addon to work properly on "Live Channels" or "PVR Live" app?

**Comment by iMro0t** [comment]
Tl;dr  NO

Kodi doesn't support this kind of integration. Regarding the m3u playlist which is required some tweaks for headers to work, and this is not possible directly via m3u.
