### ISSUE TITLE
Can I use this add-on on Australia jiotv

### ISSUE THREAD

**Issue by 17brooksedge** [botallen/repository.botallen#162]
Hello can I use your playlist in Australia ?
If so can I buy the VIP pack ?
Also jiotv add-on can I use in Australia if I have jiotv login from India ?
Does it work in Australia as I need indian channels and I have Jiotv login 
I tried your add-on and added jio login but channels does not work 
Please help 

Also I cannot send message on your discord channels as it says I cannot add server and I am not your friend 
Please help email me on 17brooksedge@gmail.com

**Comment by iMro0t** [comment]
Streams are Geo-restricted. So you must be on Indian network while playing channels.

**Comment by 17brooksedge** [comment]
Can I use vpn India??
