### ISSUE TITLE
star channels not working 

### ISSUE THREAD

**Issue by saksham2323h** [botallen/repository.botallen#165]
kodi version- 19.1
os-android
I have downloaded both the addons (jio tv and hotstar) and logged in to it. whenever I play a star channel it gives a notification of " use jio network to play this content". please fix this issue as soon as possible i dont have a disney hotstar vip/premium sibscription

**Comment by iMro0t** [comment]
It's already showing what to do. From Jiotv official app you can only play star channels on their network only. So this is the exact same thing.

**Comment by saksham2323h** [comment]
> It's already showing what to do. From Jiotv official app you can only play star channels on their network only. So this is the exact same thing.

i am using this on tv and with wifi (not jio fiber) what to do?
