### ISSUE TITLE
catchup programs

### ISSUE THREAD

**Issue by saksham2323h** [botallen/repository.botallen#167]
## Feature request
For Add-on- jio tv v2.2.1 ... [e.g. Jiotv]
I'm submitting a proposal to ... add catchup programs older than 1 day as jio tv offers catchup of 7 days

**Comment by fatalcoder524** [comment]
@saksham2323h It's already present for channels which have catchup. Goto Jio TV addon. Select the channel and long press to get catchup options.

**Comment by saksham2323h** [comment]
> @saksham2323h It's already present for channels which have catchup. Goto Jio TV addon. Select the channel and long press to get catchup options.

can u please explain the steps as I am not able to find it (channel - sony sab hd)

**Comment by fatalcoder524** [comment]
Goto My Add-ons -> Video Add-ons -> Jio TV -> Open -> Languages -> Hindi -> long press on Sony SAB HD -> Catchup -> select the day or show you wanna watch

**Comment by saksham2323h** [comment]
can I show these programs in the guide menu of the channel?
