### ISSUE TITLE
catchup programs

### ISSUE THREAD

**Issue by saksham2323h** [botallen/repository.botallen#168]
## Feature request
For Add-on ... jio tv
I'm submitting a proposal to ... integrate the catchup programs in guide menu

**Comment by iMro0t** [comment]
![screenshot00000](https://user-images.githubusercontent.com/25949138/128304003-b9f22495-8f62-4d29-a3c0-1b0c8ffa037e.png)

It's already present. Go to add-on settings and select Setup PVR. Also it only works in Kodi 19

**Comment by saksham2323h** [comment]
I have done it but it only shows catchup programs from past 1 day only but when going to My Add-ons -> Video Add-ons -> Jio TV -> Open -> Languages -> Hindi -> long press on Sony SAB HD -> Catchup it show catchup programs of past 7 day. I am asking to integrate all the seven days in the guide menu
