### ISSUE TITLE
No English audio stream on Hotstar

### ISSUE THREAD

**Issue by gideon793** [botallen/repository.botallen#17]
Is it possible to get an English audio stream on Hotstar? I only get options for Hindi, Tamil and Telugu.

**Comment by botallen** [comment]
Will look into that and try to fix it asap

**Comment by botallen** [comment]
> Is it possible to get an English audio stream on Hotstar? I only get options for Hindi, Tamil and Telugu.

![image](https://user-images.githubusercontent.com/60690413/79733222-67106880-8312-11ea-9c97-b2d3cff3781f.png)

For English audio hotstar premium subscription is required

**Comment by gideon793** [comment]
I do have a premium account. How do I activate that?

**Comment by botallen** [comment]
> I do have a premium account. How do I activate that?

You don't have to activate that. This is a bug i'll fix it soon
