### ISSUE TITLE
Disney plus hotstar

### ISSUE THREAD

**Issue by jawbreaker19** [botallen/repository.botallen#172]
**Your Environment**
- Add-on name: [Disney plus hotstar]
- Add-on version: [2.0.0]
- Kodi version: [Kodi 19]
- Operating system version/name: [android 9]
- Using from country: [ India..]

**Describe the bug**
A clear and concise description of what the bug is. Star channels are working ..... Asking for jio network

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**
![Screenshot_20210806-115401](https://user-images.githubusercontent.com/60437583/128467602-9b5e7d3f-c909-41f2-a36c-9282d99fea63.jpg)

**Additional context**

**Debug log**

The debug log can be found from this link:

**Comment by saksham2323h** [comment]
i have the same issue in my android tv

**Comment by iMro0t** [comment]
Hotstar doesn't offer live channels officially on their website or on any other platform even if you have VIP or Premium. The only way to play these channels is to play via the Jio network so this is not a bug but a kind of feature that you can watch live channel if you are using the Jio network

**Comment by jawbreaker19** [comment]
Can you please add one more addon of airtel live tv like jio tv

**Comment by karthik-aithal** [comment]
@iMro0t 
Is star channels still streaming through jio fibre(using Kodi)? or we need both active hotstar plan + Jio network?
