### ISSUE TITLE
no HD stream for Jio Tv , max quality is 480p

### ISSUE THREAD

**Issue by aranyaskr7** [botallen/repository.botallen#182]
## Feature request
For Add-on ... [e.g. Jiotv]
I'm submitting a proposal to ...
  - [ ] new feature
  - [ ] change an existing feature

#### Development tips
Not obligatory, you can describe how you would develop it, attach links to already prepared code, etc...

**Comment by markiv24** [comment]
Jio itself is broadcasting in 480p or 520p hence nothing can b done

**Comment by jzusamaniusmani** [comment]
how i can get user name and password of jio tv

**Comment by iMro0t** [comment]
Duplicate of #132

**Comment by roshan2609** [comment]
> Jio itself is broadcasting in 480p or 520p hence nothing can b done

this is a wrong statement, many channels run at 720/1080 both on jio tv app and using botallen on koditv for windows

**Comment by roshan2609** [comment]
![image](https://user-images.githubusercontent.com/91686031/141289932-380c7fa4-4df9-4b82-b2f0-acc2a45474d4.png)
