### ISSUE TITLE
Jio addon now working on non jio network

### ISSUE THREAD

**Issue by pshewale-dev** [botallen/repository.botallen#186]
Jio tv addon not working on non jio network.
Channel loading
![16296973485154376131229791135717](https://user-images.githubusercontent.com/79329378/130396341-a46775e3-85df-4874-a259-d4823805e24f.jpg)

**Comment by iMro0t** [comment]
It's working on all networks currently. Please provide more details with debug log if possible. It could be a different issue

**Comment by pshewale-dev** [comment]
Issue from isp and fixed it from them
