### ISSUE TITLE
No zip file in repository link

### ISSUE THREAD

**Issue by abrolmighty1234** [botallen/repository.botallen#188]
**Your Environment**
- Add-on name: [e.g. Jiotv]
- Add-on version: [e.g. 2.0.0]
- Kodi version: [e.g. Kodi 19]
- Operating system version/name: [e.g. Windows 10, LibreElec 9.0, etc...]
- Using from country: [eg. India, USA, etc...]

**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Additional context**

**Debug log**

The debug log can be found from this link:

**Comment by kedarbhise** [comment]
Tried this on 2021-08-29 using OSMC 2021-08 on Raspberry Pi 3.

The File Manager in Settings was successfully able to locate the zip file at the repository link.

**Comment by abrolmighty1234** [comment]
Thanks a lot for a kind concern
Recently got it rechecked and now I am able to find the zip file in the
repository again
Thanks a lot
