### ISSUE TITLE
Login Procedure in Hotstar

### ISSUE THREAD

**Issue by Vikassm73** [botallen/repository.botallen#19]
Do I have to do login procedure once only?? or every time I start the app.?

**Comment by adbaditya** [comment]
You just have to login once.

**Comment by botallen** [comment]
@Vikassm73 You have to login once only.
Also i read your comment on mani's plugin you were trying to get playback. But as you told that you have to get login token and it expires after some time. So it's same as this plugin do ( with disney+ support obviously ). If you still want to know full procedure then you can contact me here hotstar@botallen.com :)

**Comment by Vikassm73** [comment]
@botallen I have seen your code. It can not be done without valid login. I was trying like a web page where we can able to play a free content.

**Comment by Vikassm73** [comment]
@botallen Able to tweak your code to use it for free (Like android app). Working fine since more than a week. Let's see

**Comment by botallen** [comment]
> @botallen Able to tweak your code to use it for free (Like android app). Working fine since more than a week. Let's see

For all premium and vip content ?

**Comment by Vikassm73** [comment]
No.  Just Free content will be played. No login required.

**Comment by botallen** [comment]
> No. Just Free content will be played. No login required. Just like Mani's addon

You can create pull request if you want to contribute

**Comment by Vikassm73** [comment]
#37
