### ISSUE TITLE
connection error maximum connection retrieved from this url

### ISSUE THREAD

**Issue by jaspreet342141** [botallen/repository.botallen#190]
**Your Environment**
- Add-on name: [e.g. Jiotv]
- Add-on version: [e.g. 2.0.0]
- Kodi version: [e.g. Kodi 19]
- Operating system version/name: [e.g. Windows 10, LibreElec 9.0, etc...]
- Using from country: [eg. India, USA, etc...]

**Describe the bug**
connection error maximum connection retrieved from this url getting the same error on all of the device even with different jio account

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Additional context**

**Debug log**

The debug log can be found from this link:

**Comment by nbalakrishnan78** [comment]
I am facing this error from this morning.

**Comment by jaspreet342141** [comment]
I think it's fixed now it was a problem from jio TV itself I couldn't login in jio TV with my wifi  @nbalakrishnan78 but now it's working fine

**Comment by nbalakrishnan78** [comment]
> I think it's fixed now it was a problem from jio TV itself I couldn't login in jio TV with my wifi  @nbalakrishnan78 but now it's working fine

Thank you very much for quick reply. Have a great day

**Comment by jaspreet342141** [comment]
@nbalakrishnan78  is your issue also fixed

**Comment by nbalakrishnan78** [comment]
> @nbalakrishnan78  is your issue also fixed

Yes. The issue is fixed.
