### ISSUE TITLE
ConnectionError

### ISSUE THREAD

**Issue by Bhavin213** [botallen/repository.botallen#193]
**Your Environment**
- Add-on name: [e.g. Jiotv]
- Add-on version: [e.g. 2.0.0]
- Kodi version: [e.g. Kodi 19]
- Operating system version/name: [e.g. Windows 10, LibreElec 9.0, etc...]
- Using from country: [eg. India, USA, etc...]

**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Additional context**

**Debug log**

The debug log can be found from this link:

https://user-images.githubusercontent.com/41487075/131339976-397da250-ab44-49e5-a0b0-abbaaed5839d.mp4

**Comment by jaspreet342141** [comment]
this will be fixed soon this is a problem from jio TV itself
for some reason it has been happening often
but if you want to fix rn it you need to change your DNS server
to cloudflare DNS server 
it is 1.1. 1.1 and 1.0. 0.1

**Comment by Bhavin213** [comment]
thanks, bro now it's properly working...

**Comment by jaspreet342141** [comment]
yep it's fixed now did you change your DNS or it automatically got fixed @Bhavin213

**Comment by Bhavin213** [comment]
no, I change the DNS

**Comment by Bhavin213** [comment]
> yep it's fixed now did you change your DNS or it automatically got fixed @Bhavin213
no, I change the DNS

**Comment by jaspreet342141** [comment]
> > yep it's fixed now did you change your DNS or it automatically got fixed @Bhavin213
> > no, I change the DNS

oh ok ok
