### ISSUE TITLE
Airtel

### ISSUE THREAD

**Issue by SatwikJha** [botallen/repository.botallen#2]
Bro, just like you have made a jiotv addon can you also please make a airteltv addon

**Comment by botallen** [comment]
I will do it later for whole airtel xtream content. Have to find airtel xtream user first 😅

**Comment by SatwikJha** [comment]
Ok,Thank you for replying

But your jiotv addon is just amazing
Can, I know what are your future plans for Kodi addons

**Comment by botallen** [comment]
Not sure. Will update in this repo .

**Comment by SatwikJha** [comment]
Hello,
    Can you please tell me how to use your hotstar Kodi addon.?
