### ISSUE TITLE
Cant access TataSky channels displays "Access denied"  and does not work through Jio Fiber network.

### ISSUE THREAD

**Issue by porusbaker** [botallen/repository.botallen#201]
**Your Environment**
- Android version: Android TV
- Operating system version/name: Android TV 9
- Using from country: India
- Network: JioFiber
- IPTV Application: OTT Navigator (Google Playstore), Tivimate (Google Playstore)

**Describe the bug**
Cant access TataSky channels displays "Access denied"  and does not work through Jio Fiber network.

**To Reproduce**
Installed OTT Navigator on mobile and playing using Airtel network.

**Expected behavior**
Should work seamless while playing through a playlist

**Comment by iMro0t** [comment]
Only raise Kodi repository add-on related issues here
