### ISSUE TITLE
Disney Plus hotstar is not installing

### ISSUE THREAD

**Issue by iamsahilohe** [botallen/repository.botallen#21]
it's shows "The dependency script.module.inputstreamhelper 0.4.5 could not be satisfied"

**Comment by botallen** [comment]
In which device and operating system you are using kodi ?

**Comment by iamsahilohe** [comment]
Raspbian (Raspberry Pi 3 Model B+

**Comment by iamsahilohe** [comment]
and script.module.win_inet_pton shows not available.

**Comment by botallen** [comment]
> Raspbian (Raspberry Pi 3 Model B+

Give me your email i'll give you workaround add-on. But you still need repository installed.
I'll fix this in next release

**Comment by iamsahilohe** [comment]
Mail - sahilohe97@gmail.com

**Comment by botallen** [comment]
@iamsahilohe check your mail. I just sent you a zip file. If you are facing any other issue then feel free to reopen this issue

**Comment by iamsahilohe** [comment]
The video is not playing

**Comment by iamsahilohe** [comment]
any of the video is not playing

**Comment by botallen** [comment]
Give me log file. In raspberry pi are you using with OSMC?

**Comment by iamsahilohe** [comment]
no I'm using the kodi app (sudo apt install kodi)

**Comment by botallen** [comment]
> no I'm using the kodi app (sudo apt install kodi)

I guess you have old kodi version and i didn't consider backward compatibility yet. So you need to update kodi (v18.6)

**Comment by iamsahilohe** [comment]
its already on 18.6

**Comment by iamsahilohe** [comment]
only hotstar doesnt work, jio tv works fine

**Comment by botallen** [comment]
Give me log file then i can only help by understanding your problem
