### ISSUE TITLE
Please make hotastar free without subscription

### ISSUE THREAD

**Issue by rethu123** [botallen/repository.botallen#211]
## Feature request
For Add-on ... [e.g. Jiotv]
I'm submitting a proposal to ...
  - [ ] new feature
  - [ ] change an existing feature

#### Development tips
Not obligatory, you can describe how you would develop it, attach links to already prepared code, etc...

**Comment by iMro0t** [comment]
Guest User support is there so whatever Hotstar provides to Guest Users will be playable without Subscription or log in. 

Playing Premium or VIP content without a subscription is not possible and will never gonna happen.

**Comment by rethu123** [comment]
Then please add Jio cinema, jiosaavn, wynk music, Aitel XStream
