### ISSUE TITLE
Does not play IPL Live

### ISSUE THREAD

**Issue by viveksuraiya** [botallen/repository.botallen#212]
I have updated the Disney+Hotstar Addon to 1.1.1. It still does not play the Star Sports channel (IPL). I have a VIP subscription via Jio Fiber.

**Comment by iMro0t** [comment]
Don't play from `Channels`. 
Go to `Sports` > `Carousel` > `x VS y Match`. 

If you still face any issues please reopen this issue. Don't create new issue.
