### ISSUE TITLE
Every time Refreshing

### ISSUE THREAD

**Issue by impurnendu** [botallen/repository.botallen#217]
Every time when I on my tv and open the Kodi App it always take time to collect the channels once again. It should be better if this process is done once forever. It's annoying to wait everytime.

**Comment by iMro0t** [comment]
@impurnendu  this is the expected behavior of PVR IPTV SImple client. You can tweak the settings to cache your channels and guide information. Please report PVR addon related issues here https://github.com/kodi-pvr/pvr.iptvsimple
