### ISSUE TITLE
Cannot Enable Subtitles and Cannot Toggle between Languages

### ISSUE THREAD

**Issue by goforrenga** [botallen/repository.botallen#22]
- Tried enabling subtitles for Tv shows both in hotstar and Disney+ but couldn't do it 

-  Some Shows plays with default hindi audio ( Tried playing Hannah Montana , disney original Tv show ) and when i tried to toggle the audio , couldn't do it . Hope you fix it

-  Overall a great work on the Add On . Cheers

**Comment by botallen** [comment]
> - Tried enabling subtitles for Tv shows both in hotstar and Disney+ but couldn't do it 
> 

Subtitles is already there but there is a problem in inputstream add-on. I have to dig into that to find actual issue

> -  Some Shows plays with default hindi audio ( Tried playing Hannah Montana , disney original Tv show ) and when i tried to toggle the audio , couldn't do it . Hope you fix it
> 

English audio is only available for premium users. And also in some case there are different version of content with different language like Taanhaji is both in Marathi and Hindi but in one stream you can toggle between hindi and Marathi and in other it's only have Marathi so you have to look for another stream

> -  Overall a great work on the Add On . Cheers 

Thanks for feedback

**Comment by goforrenga** [comment]
Please do let me know when you fix the subtitle issue . Cheers mate 👍

**Comment by titusrdx** [comment]
Waiting for subtitles fix

**Comment by kedarbhise** [comment]
Great work on the addon!

I am facing the subtitles issue in Disney+ and Hotstar as well.

I have a Premium subscription so English Audio is available, but I cannot select audio language.

**Comment by titusrdx** [comment]
Still subtitle not working for tvshows

**Comment by kedarbhise** [comment]
Same issue for me on `0.0.27`. Subtitles not working.

**Comment by botallen** [comment]
> Still subtitle not working for tvshows .

I tested on Special ops (tv show) and Lion king (movie). It's working on both. Also noticed that it's taking some time to load subtitles

**Comment by titusrdx** [comment]
tried for Prison break but fails
