### ISSUE TITLE
Unable to login to Jio TV in Kodi

### ISSUE THREAD

**Issue by d3lac** [botallen/repository.botallen#225]
**Your Environment**
- Add-on name: Jio TV
- Add-on version: 2.0.0
- Kodi version: Kodi 18.9
- Operating system version/name: Windows 10
- Using from country: India

**Describe the bug**
Unable to login to Jio TV in Kodi with password/web login.

**To Reproduce**
Try to login with Jio credentials.

**Screenshots**
https://i.ibb.co/xs9GX7f/kodi-bb-USk-AAqqh.png

**Additional context**

**Debug log**

Logs: https://0bin.net/paste/QHE06BW0#KfgYICCZlB-3Yjpd+uGNehzitJvId+pgpJ93Buan0VD

**Comment by vivinnl** [comment]
is this still an issue?

**Comment by iMro0t** [comment]
There are two kinds of scenarios that can cause this issue
1. Due to incorrect password
2. SSL error which is randomly caused due to server misconfiguration
