### ISSUE TITLE
Persistent login for Jio TV

### ISSUE THREAD

**Issue by rrjanbiah** [botallen/repository.botallen#226]
For Add-on Jiotv

I'm not sure if this is possible. Session is getting expired approximately once in two days and so had to re login again. Please see if it is possible to implement persistent login. Thanks

**Comment by iMro0t** [comment]
Persistent login is already available but you had to log in with username and password option. With OTP it's not possible.

**Comment by rrjanbiah** [comment]
@iMro0t Thanks for letting me know. But, I'm not sure how you could find the username.. perhaps, this username is remove recently?
