### ISSUE TITLE
Most of the channels are not working

### ISSUE THREAD

**Issue by Chinna-23** [botallen/repository.botallen#23]
I installed one week ago. It worked well for 2-3 days and all of a sudden now most of the channels aren't working. In Tamil on Star Vijay is working, all other channels are not working and few other channels are working. Please do check this. I would say 80% channels are not working.

**Comment by botallen** [comment]
Hey @Chinna-23 . Can you please provide me log file. Because no one is facing this kind of issue where 80% channels are not working. It's strange

**Comment by Chinna-23** [comment]
@botallen I'm not sure how to capture logs in KODI. Check all Tamil channels, and you will get an idea.

**Comment by botallen** [comment]
You mean 80% Tamil channels are not working or 80% of all channels are not working. Log will help me to catch error quickly

**Comment by Chinna-23** [comment]
Only one Tamil channel is working (Star Vijay) other than that nothing works. Please do let me know how to check logs.

**Comment by botallen** [comment]
> @botallen did you get a chance to look at my logs?

Sorry for bit late reply. Try to re login and it'll be all good

**Comment by Chinna-23** [comment]
worked.
