### ISSUE TITLE
The Windows Store version of Kodi dose not support Widevine CDM

### ISSUE THREAD

**Issue by neshgithub** [botallen/repository.botallen#234]
Error:
The Windows Store version of Kodi dose not support Widevine CDM
Please use the installer from kodi.tv instead
![Screenshot (47)](https://user-images.githubusercontent.com/20812781/145481615-67025e70-a45d-4bff-b009-630a85232dea.png)

**Comment by iMro0t** [comment]
That's a clear description of the issue. Uninstall from store and download it from here https://kodi.tv/download/windows

**Comment by 91atul** [comment]
I am also facing same issue, I already install it from kodi.tv, also check in old version but error is same. "The Windows Store version of Kodi dose not support Widevine CDM
Please use the installer from kodi.tv instead"
Please help if any one know about solution on this.
