### ISSUE TITLE
Cannot login to Hotstar

### ISSUE THREAD

**Issue by WeirdlyChosen** [botallen/repository.botallen#235]
**Your Environment**
- Add-on name: [Hotstart]
- Add-on version: [v1.1.1]
- Kodi version: [Kodi 19]
- Operating system version/name: [OSMC]
- Using from country: [Indonesia]

**Describe the bug**
Cannot login to Hotstar. 

**To Reproduce**
1. Go to Settings
2. Click on Login
3. There is "you have no subscription" notification with debug log provided
4. See an error

**Expected behavior**
activation code is shown and can be activated from browser

**Debug log**

The debug log can be found from this link:
https://pastebin.com/FbBj3RAm

**Comment by Arsyad1105** [comment]
This addon only for India. You need to modify this addon by yourself but you still need VPN to login.

**Comment by vivinnl** [comment]
@iMro0t  Please close this case.
