### ISSUE TITLE
Channels not working

### ISSUE THREAD

**Issue by shekhar771** [botallen/repository.botallen#237]
Add-on name:  Jiotv
- Kodi version: Kodi 19.3
- Operating system : android

Zee and sony channels are not working. They show loading for a few second and doesn't open.
They show loading symbol on top right of screen. Also the loading of channels at beginning also takes a very long time .  While channels from colors are still working other don't.
This is the logfile  

https://paste.kodi.tv/wanowiraxi

**Comment by iMro0t** [comment]
this issue is fixed. update to version v2.2.2

**Comment by shekhar771** [comment]
Great job man , thanks.
