### ISSUE TITLE
None of the channels are loading from 13th November's Evening.

### ISSUE THREAD

**Issue by babatunde6969** [botallen/repository.botallen#238]
**Your Environment**
- Add-on name: [e.g. Jiotv]
- Add-on version: [e.g. 2.0.0]
- Kodi version: [e.g. Kodi 19]
- Operating system version/name: [e.g. Windows 10, LibreElec 9.0, etc...]
- Using from country: [eg. India, USA, etc...]

**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Additional context**

**Debug log**

The debug log can be found from this link:

**Comment by iMro0t** [comment]
this issue is fixed. update to version v2.2.2

**Comment by babatunde6969** [comment]
Thanks for fixing it so quickly. ❤️
