### ISSUE TITLE
Issue on vande gujarat channels

### ISSUE THREAD

**Issue by Suraj824** [botallen/repository.botallen#24]
Respected friend i am using your add on from last two weeks, it is observed that vande gujarat all channels are not working, if it is possible please make it working a kind request from us. 
     Thank you!!!!

**Comment by botallen** [comment]
@Suraj824 . Just checked that none of the education channels are working. Will look into that.

**Comment by Suraj824** [comment]
Please fix the jiotv related issues not working smoothly..

**Comment by bhargav1822** [comment]
I dont require now jiotv+

Please fix all bugs from normal jio tv add-on
Make it play like cable tv
Thank you
