### ISSUE TITLE
Jio Tv not working 

### ISSUE THREAD

**Issue by CoderYash123** [botallen/repository.botallen#242]
**Your Environment**
- Add-on name: [e.g. Jiotv]
- Add-on version: [e.g. 2.0.0]
- Kodi version: [e.g. Kodi 19]
- Operating system version/name: [e.g. Windows 10, LibreElec 9.0, etc...]
- Using from country: [eg. India, USA, etc...]

**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Additional context**

**Debug log**

The debug log can be found from this link:

**Comment by sonulohani** [comment]
I am also facing the same issue

**Comment by 0harshkumar0** [comment]
bro just reinstaal jio tv addon and login again and setup then u good to go

**Comment by sonulohani** [comment]
I did that but still no success

**Comment by sonulohani** [comment]
> bro just reinstaal jio tv addon and login again and setup then u good to go
> 

Btw is it working for you

**Comment by saumilwaghela** [comment]
@0harshkumar0 @iMro0t , Device: Android, tried reinstalling kodi 19.3, Jio v2.2.2, tried connection with vpn (foreign), vpn india, without VPN, it throws play back failed, one or more items failed to play.  on back logs I could see plugin.jio.tv url failing http 406
`2021-12-14 18: 45: 04.253 T: 29218 INFO

files/.kodi/addons/plugin.video. jiotv/ <general>: CPython Invoker (2, /storage/ emulated/0/Android/data/org.xbmc.kodi/ files/.kodi/addons/plugin.video.jiotv/ addon.py): script successfully run <general>: VideoPlayer::Open File: plugin:// plugin.video.jiotv/resources/lib/main/play/ ?pickle-80049529000000000000007d94288c075 f7469746c655f948c07536f6e79204844948c0a6368 616e6e656c5f6964944d2301752e 2021-12-14 18:45:05.511 T:29313 <general>: Creating InputStream 2021-12-14 18:45:06.412 T:29313 <general > CCurlFile::FillBuffer HTTP returned error 406 <general: CCurlFile::FillBuffer - Reconnect, (re)try 1 Failed:

INFO

ERROR

2021-12-14 18:45:06.413 T:29313 WARNING

2021-12-14 18:45:06.757 T:29313 ERROR

<general»: CCurlFile::FillBuffer- Failed: HTTP returned error 406

2021-12-14 18:45:06.758 T:29313 ERROR

<general»: CCurlFile:: Open failed with code 406 for https://jiotv.live.cdn.jio.com /packagerx_mpd3/Sony_HD_HLS/Sony_HD.m3u8 ?jct=Ukwn22UP0dBsAF6By3rrqw&pxe=1639520823& st=9p-0_v1qIyd6E-rf8_gEOQ:`




Similar to :https://github.com/botallen/repository.botallen/issues/105

![image](https://user-images.githubusercontent.com/36496816/146005476-b945db5c-2802-4868-80e9-659b66969a65.png)

**Comment by saumilwaghela** [comment]
got it fixed by following below step
Since URL was working fine I needed no vpn case may different for other
Before starting ensure that you have updated your official jio tv app and have logged in with your sim on your phone
Now in your tv, follow steps and install this repo. Do login and try once to start channel
If doesn't then follow below....
Goto add on-- pvr client--- download IPTV simple client and once installation done goto add on jiotv long press on it goto Setup and choose simple IPTV option. It will ask you to restart kodi... Exit the app from power button on top left and sometimes it hangs wait for 20 sec if it doesn't go then kill the app...
Open and test
It worked for my case

**Comment by ABHI1152** [comment]
I tried everything but Reinstall is only option it worked for me .

**Comment by sonulohani** [comment]
Thanks working now.

**Comment by iMro0t** [comment]
Update to v2.2.2 and re-login should fix the problem

**Comment by CoderYash123** [comment]
Starts working after reinstalling the app

**Comment by adityapv** [comment]
Here's what worked for me:

- Reinstall PVR IPTV Simple Client by going to Add-ons -> My add-ons -> PVR IPTV Simple Client -> Versions
- Login to JioTV addon again from Video add-ons, select and long-press JioTV -> Settings -> Account -> Login
- Comeback to JioTV Settings, select Setup -> Setup Simple IPTV PVR. A notification will appear stating 'Playlist updated, Restart to apply the changes.
- Exit Kodi or remove it from memory
- Launch again

**Comment by vineetmalviya** [comment]
For me, I unchecked the option Extra HD channels in Extra settings for the add on.
That seems to work for me

**Comment by arenprasad** [comment]
Earlier i could watch the past tv programs by going to the past program and clicking on play channel . By one fine morning , live tv I can watch not the past channels. I installed kodi, upgraded to 19.5 version several times . But I failed and gave up. I am really sad and frustrated . I have tried all the suggestions given by you friends, but couldn't succeed .
