### ISSUE TITLE
same for me. any solution on this.

### ISSUE THREAD

**Issue by 29Unknown29** [botallen/repository.botallen#244]
Yes, downloaded simple IPTV addon from Kodi repo, but not working. It showing the list of channels and none playing.

_Originally posted by @chamaraju in https://github.com/botallen/repository.botallen/issues/163#issuecomment-993574253_

**Comment by iMro0t** [comment]
@29Unknown29 Please provide more information about the issue. Make sure you are using Kodi 19.X and Jiotv addon v2.2.2

**Comment by adityapv** [comment]
Here's what worked for me (Kodi Ver. 19.3.0 Matrix) :

- Reinstall PVR IPTV Simple Client by going to Add-ons -> My add-ons -> PVR IPTV Simple Client -> Versions
- Login to JioTV addon again from Video add-ons, select and long-press JioTV -> Settings -> Account -> Login
- Comeback to JioTV Settings, select Setup -> Setup Simple IPTV PVR. A notification will appear stating 'Playlist updated, Restart to apply the changes.
- Exit Kodi or remove it from memory
- Launch again

**Comment by musky603** [comment]
> Here's what worked for me (Kodi Ver. 19.3.0 Matrix) :
> 
> * Reinstall PVR IPTV Simple Client by going to Add-ons -> My add-ons -> PVR IPTV Simple Client -> Versions
> * Login to JioTV addon again from Video add-ons, select and long-press JioTV -> Settings -> Account -> Login
> * Comeback to JioTV Settings, select Setup -> Setup Simple IPTV PVR. A notification will appear stating 'Playlist updated, Restart to apply the changes.
> * Exit Kodi or remove it from memory
> * Launch again

Thanks a ton It successfully works ( Note- First I thought only Jiotv addon update work but it failed then I tried your method alongwith clearing cache memory of Kodi app & restarting both app and android device so after loading the full app properly it successfully works )

**Comment by vivinnl** [comment]
@iMro0t  Please close this case.
