### ISSUE TITLE
PVR takes long time to load up channels

### ISSUE THREAD

**Issue by tayde24** [botallen/repository.botallen#247]
**Your Environment**
- Add-on name: JioTV 2.2.2
- Add-on version: 2.2.2
- Kodi version: 19.3
- Operating system version/name: xbian
- Using from country: India

**Describe the bug**
After login in jio tv, I had set up simple IPTV pvr from jio tv configuration. Restarted my system. However, as the system starts, pvr starts loading channels, stating in right corner that importing guide from clients. The progress is shown in percentage. It takes around 10 minutes to completes after which I can watch channels.

**Expected behavior**
Normally when I was using earlier version of JioTV on osmc, it was used to complete the loading in 10-20 seconds.

**Screenshots**

**Additional context**

**Debug log**

The debug log can be found from this link:

**Comment by iMro0t** [comment]
Try using compressed EPG. Refer to this https://github.com/botallen/repository.botallen/issues/250#issuecomment-1001159527

Still, it won't be fast compared to other players. Maybe create a separate issue here https://github.com/kodi-pvr/pvr.iptvsimple
