### ISSUE TITLE
Jio TV addon is not working at all on LibreELEC.. There is no current Matrix version for LibreELEC.. How can we fix this? 

### ISSUE THREAD

**Issue by AmmanRaikar** [botallen/repository.botallen#248]
I've tried all the solutions listed everywhere to fix this issue.. I've even re installed the whole kodi system just to make this work.. But it seemingly isn't working out for me... Is there a way to fix this issue on Kodi Liea?.. Please help me out here

**Comment by shridattdudhat** [comment]
Hi, I am facing same issue with JioTV, It does not play any channel from last one week,

**Comment by RockStock143** [comment]
Same issue faced on LibreElec;

**Comment by tech-yashui** [comment]
Facing the same issure from 10 days jio tv is not working please help me out

**Comment by shridattdudhat** [comment]
It is working in LibreELEC v10 but not in v9.2, Sadly LibreELEC v10 is not supported in rpi3,

I flashed v10 in rpi3 and somehow manage to play jio tv there but its is buggy and the audio is disabled.

**Comment by iMro0t** [comment]
Unfortunately, the latest version of Jiotv will only work in Kodi 19 which is not backward compatible. 
You can try using OSMC which has the latest Kodi Matrix version and is also available for rpi3

**Comment by shridattdudhat** [comment]
> Unfortunately, the latest version of Jiotv will only work in Kodi 19 which is not backward compatible. You can try using OSMC which has the latest Kodi Matrix version and is also available for rpi3

@iMro0t Thank you for the suggestion, I will try on OSMC and will post the result here.

**Comment by RockStock143** [comment]
> Unfortunately, the latest version of Jiotv will only work in Kodi 19 which is not backward compatible. You can try using OSMC which has the latest Kodi Matrix version and is also available for rpi3

Spot on! Did some trial and error on LibreElec and then switched to OSMC; It is working fine now; even few issues of Hotstar are fixed.

**Comment by tech-yashui** [comment]
how to install osmc on amazon fire tv stick

**Comment by AmmanRaikar** [comment]
I tried installing osmc which has Kodi Matrix but it is not at all loading up.. I'm using a rpi 3b+ and osmc doesn't seem to load up after the inital install... Just a blank screen.. could anyone help me out with this?
Has anyone else gone through the same issue?

**Comment by AmmanRaikar** [comment]
Well, I fixed the issue. The issue wasn't with libreelec but was with my television itself. You see, libreelec v10 sets the resolution to 1920x1080 or some other hd/4k resolution(I don't know the fact exactly and i apologize) .. But you can fix it by adding a line to the cmdline.txt file.. video=HDMI-A-1:1280x720@60D (This worked for me, cause i wanna use hdmi and my television supports 1280x720, but i suggest you look through some forums if this doesn't work.. Look up "force resolution using cmdline libreelec") .. I'm gonna close this thread now so i hope I was able to help anyone in need. 

https://forum.libreelec.tv/thread/23910-no-vid%C3%A9o-signal/?pageNo=2
I used this thread to fix my issues.. It has most of the links I used and I hope this can help
