### ISSUE TITLE
Jio tv stb links bug

### ISSUE THREAD

**Issue by Suraj824** [botallen/repository.botallen#25]
Respected friend it is observed that when i am using stb links (auto,  stb option in configuration), it is automatically close after some time. please take it this issue in count. 
      Thank you!!!

**Comment by botallen** [comment]
I am planning to drop major jiotv+ release with jio cinema integration. Wait until that release and all issue will be solved

**Comment by nepalicana** [comment]
Thank you @botallen for your wonderful addons. Looking forward for the jio cinema addons. Take care. Btw I also wanted to make an addon. Would u please tell me which language package do u use to write your addons?

**Comment by botallen** [comment]
Jiotv+ beta is out now. Check it out in my repo

**Comment by Suraj824** [comment]
It will require jio fiber??? Showung error while opening.

**Comment by bhargav1822** [comment]
Should i use jio id??

**Comment by botallen** [comment]
There is problem in login functionality. Try couple of times and you'll be logged in

**Comment by botallen** [comment]
> It will require jio fiber??? Showung error while opening. 

No it doesn't require jio fiber network or any jio fiber set-top box plan.

**Comment by Suraj824** [comment]
It is possible to available iptv client for jiotv + live tv category??? If it is possible please make it a kind request from ys... 



And thank you so much for jiotv+
