### ISSUE TITLE
Guide list is not working. Not able to watch previous programs

### ISSUE THREAD

**Issue by Theron142** [botallen/repository.botallen#252]
**Your Environment**
- Add-on name: [e.g. Jiotv]
- Add-on version: [e.g. 2.0.0]
- Kodi version: [e.g. Kodi 19]
- Operating system version/name: [e.g. Windows 10, LibreElec 9.0, etc...]
- Using from country: [eg. India, USA, etc...]

**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Additional context**

**Debug log**

The debug log can be found from this link:

**Comment by sudhakarsi** [comment]
This issue is a Christmas gift startef on 25 Dec

**Comment by iMro0t** [comment]
Guide data is available now
