### ISSUE TITLE
HD channels stop playing

### ISSUE THREAD

**Issue by gpkumaran** [botallen/repository.botallen#26]
Thank you first of all. I saw a peculiar occurrence. I used to watch comedy Central HD and Sun HD. Sometimes cc hd is not available and during that time I'm able to play Sun HD and vice versa. And when sun HD is unavailable, cc hd is able to play. Even while playing, either channels just stop for sometime (like 1 to 5 sec) in the middle and then start playing again. No prob with the internet. Having 100mbps fibre

**Comment by botallen** [comment]
I am planning to drop major jiotv+ release with jio cinema integration. Wait until that release and all issue will be solved
