### ISSUE TITLE
Cannot login to JioTV

### ISSUE THREAD

**Issue by vivinnl** [botallen/repository.botallen#262]
**Your Environment**
- Add-on name: JioTV
- Add-on version: 2.0.0
- Kodi version: Kodi 19 Matrix
- Operating system version/name: Android TV 9
- Using from country: India
- ISP & Bandwidth: KeralaVision Broadband , 40 Mbps

**Describe the bug**
From yesterday eve IST, I am not able to login to my JioTV account from JioTV Kodi addon using ISP's other than JioFibre or Jio Mobile Hotspot, I tried this in 2 different TV connected in 2 different Indian regions.
I tried both the Web & Keyboard login methods provided by JioTV addon, in both the methods after we type in the mobile number for authentication, the next screen i.e the OTP entering screen does not show up nor the OTP is sent to the provided Jio mobile number.
I get the same issues with Vanilla Kodi 19 Matrix.
Due to this we are not able to watch any channels from this addon.

**To Reproduce**
1. Connect your Kodi to ISP's other than JioFibre or Jio Mobile Hotspot
2. Choose any one of the Web & Keyboard login methods provided by JioTV addon.
2. Type in the mobile number for authentication.
3. The next screen i.e the OTP entering screen does not show up nor the OTP is sent to the provided Jio mobile number.

**Expected behavior**
Login successfully to JioTV account in JioTV Kodi addon using all ISP's and watch TV channels as before.

**Workaround**
Just for login use JioFibre or Jio Mobile Hotspot in Kodi after which any ISP's can be used to watch channels.

**Debug log**
The debug log can be found from this link:
https://leancoding.co/KZIHSZ

**Comment by vivinnl** [comment]
its been resolved now, looks like temporary glitch. :-)

**Comment by iMro0t** [comment]
Duplicate of #225
