### ISSUE TITLE
Botallen TV App

### ISSUE THREAD

**Issue by Rakesh8181** [botallen/repository.botallen#269]
Dear Team,

Botallen TV App is very nice,

But There is issue to use,Because wi cant find any channel imediatly,its so hard to find channel,

also when i openthis app in fire tv stick app after 5 minute fire tv stick  goes on sleep mode automaticaly,

so please resolve this issue ASAP...

**Comment by iMro0t** [comment]
This repository is only for Kodi add-ons. Only raise issues related to add-on. For BotAllenTV app use the discord channel https://discord.gg/7dscB3wV
