### ISSUE TITLE
Issue regarding stb links

### ISSUE THREAD

**Issue by Suraj824** [botallen/repository.botallen#27]
If u will add jiotv+ add on then it will require jio fiber or jio fiber id?? 

Please fix the your ongoing jiotv add on in following issue:-

Stb links are auto down after some time.

Alsi high stream is stucking after some time

And a request to you please add airtel tv xtream app and airtel tv add on as soon as possible. 

Thank you!!!

**Comment by botallen** [comment]
https://github.com/botallen/repository.botallen/issues/26#issuecomment-620001116
