### ISSUE TITLE
OTP login method for For Libreelec version 18.9

### ISSUE THREAD

**Issue by rajurokr** [botallen/repository.botallen#274]
**Your Environment**
- JIOTV
- Add-on version: 2.0.0
- Kodi version: 18.9
- Operating system version/name: LibreElec 9.0
- Using from country: India

**Describe the bug**
When we install the latest botallen repository in the Librelec 9 version , The JioTV repository gets installed successfully however the login method is still the user id and password. Fo which i am unable to login in to the JIOTV repository

However in the Libreelec 10 and Kodi 19 this is already updated and the login with OTP works fine.

**To Reproduce**
1. Install Bot allen repository in Libreelec 9 with kodi version 18.9
2. try login into Jio TV addon
3. Provide the mobile number 
4. it prompts for Password 

**Expected behavior**
After the enter mobile number , it should prompt for password

**Comment by iMro0t** [comment]
OTP-based login method is added in the recent version of the add-on after v2.0.0. Use latest version
