### ISSUE TITLE
SonyLiv channels quality difference

### ISSUE THREAD

**Issue by ajinkyaambatwar** [botallen/repository.botallen#275]
## Feature request
For Add-on ... [e.g. Jiotv]
I'm submitting a proposal to ...
  - HD quality(or alteast close to it) for SonyLiv channels on KODI

#### Is your feature request related to a problem? Please describe.
I understand that it's a duplicate of #132 
I have KODI and BotAllen installed on my Android TV. I had this video quality issue there but after changing the setting to MANUALLY SELECT VIDEO STREAM and enabling ENABLE EXTRA HD CHANNELS I was (actually) able to get really good video quality on a 42 inch TV screen.
 I recently installed the app in Ubuntu laptop and did the same settings but it does not seem to work here. 

#### Describe the solution you'd like
Can you kindly check if I can achieve HD quality?

#### Describe alternatives you've considered
Already noted abve

**Comment by iMro0t** [comment]
refer to this first https://github.com/botallen/repository.botallen/issues/132#issuecomment-826751544

> MANUALLY SELECT VIDEO STREAM

With this option, you can select the maximum available resolution of the stream.

> ENABLE EXTRA HD CHANNELS

Only a few channels are actually having 1080p stream. With this option, you can use those channels.
