### ISSUE TITLE
No audio while playing video on Disney+Hotstar

### ISSUE THREAD

**Issue by vinodbadola22** [botallen/repository.botallen#28]
Hi sir,
There is no Audio In most of the latest english and hindi movies while playing Movie in Disney+ Hotstar.

**Comment by botallen** [comment]
I check it and find that they added some extra security layer to audio. Will fix that soon

**Comment by hsevna** [comment]
Replying to this thread to get notified once you fix this.

**Comment by vinodbadola22** [comment]
Fixed and working fine. Thanks a ton sir :-) Superb & Amazing job done.

**Comment by vinodbadola** [comment]
Hi Sir, Thanks for making this Jio TV, wonderful app. I have been facing some problem in playing most of the channels like new channels, AndTV and many more from past 4-5 days.

Request your help.
