### ISSUE TITLE
Jio TV not playing - solution

### ISSUE THREAD

**Issue by tesla897** [botallen/repository.botallen#280]
- Add-on name: Jiotv
- Add-on version: 2.0.0
- Kodi version: Kodi 19
- Operating system version/name: Windows 10
- Using from country: India

**Describe the bug**
Solution for Jio TV not playing

**To Reproduce**
Here's what everyone who is facing Jio TV issue needs to do:
1. Go to Addons Package Manager
2. Install from Kodi Repository
3. Scroll down to VideoPlayer Input Stream
4. Install Input Stream Adaptive
5. Run the stream again and it should work.

**Expected behavior**
@iMro0t - Please add Input Stream Adaptive as a dependency for the addon. The Input Stream Helper isn't enough.

**Comment by iMro0t** [comment]
fixed in https://github.com/botallen/plugin.video.jiotv/commit/fb0d191181da660f728d04e2c096409332c52c33
