### ISSUE TITLE
&PicturesHD, VH1HD and &TVHD has stopped working. Receiving Error: 400 bad request

### ISSUE THREAD

**Issue by adityapv** [botallen/repository.botallen#285]
- Add-on name: Jiotv
- Add-on version: 2.0.0
- Kodi version: Kodi 19.3
- Operating system version/name: Android TV 9
- Using from country: India
Note: Issue occurs when 'Extra HD Channels' feature is on. However, with this feature turned off, resolution is maxed at 1280*720 and only in HD Channels. For other channels that were not HD, resolution can't go past 576p

**Comment by Ahamprateek** [comment]
Disable the extra HD channels from the settings in JIO tv add-on, then it will work perfectly.

**Comment by adityapv** [comment]
Yes I have done the same for now, but it won't go past 720p for HD channels and many other HD channels show up in less than 720p resolution

**Comment by Ahamprateek** [comment]
https://forum.kodi.tv/showthread.php?tid=174859&page=21 ,please check this and if you get it then share with me.
