### ISSUE TITLE
Episode list shows only 20 episodes

### ISSUE THREAD

**Issue by gideon793** [botallen/repository.botallen#29]
The list shows only 20 episodes even though the season may have more (as shown by the number in the brackets at the top).

**Comment by botallen** [comment]
They have inconsistent next page logic in their api. Sometimes starts with 0 and sometimes 1. Will fix that soon 🍻

**Comment by Vikassm73** [comment]
Request you to add Episode Number in the title
Also, in the movies section, I don't find Marathi movies folder

**Comment by botallen** [comment]
> Request you to add Episode Number in the title
Yeah sure. Added in todo.
> Also, in the movies section, I don't find Marathi movies folder
because hotstar doesn't have anything like that. It's showing same as you will see in android tv app.

**Comment by Vikassm73** [comment]
Thanks Botallen

For above error you can change following code in api - gettray

nextPageUrl =  results['assets'].get("nextOffsetURL") if results.get("assets") else results.get("nextOffsetURL")
