### ISSUE TITLE
EPG problem with jiotv, any other help pls

### ISSUE THREAD

**Issue by Madmimomana** [botallen/repository.botallen#297]
**Your Environment**
- Add-on name: [e.g. Jiotv]
- Add-on version: [e.g. 2.0.0]
- Kodi version: [e.g. Kodi 19.3)
- Operating system version/name: [androidtv os 9]
- Using from country: [India]

**Describe the bug**
No guide showing for jiotv, fully blank only channel name and icon is shown, this happens in channels mode not in guide mode, and while playing channels also not able to see guide option in bottom row and info also not showing any information..

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Additional context**
I know this repository is now on not gonna be maintained by iMroot, but if any other could take this issue and fix would be great, any other coders pls help with this issue, we need these channel's, if available in ott could have opt for those, but these channel's aren't available on any ott, pls help..

**Debug log**

The debug log can be found from this link:

**Comment by ParthivSavani** [comment]
@iMro0t Facing same issue. Please help. Thanks

**Comment by arenprasad** [comment]
I am also facing in jio tv add-on , guide is only showing channels, informations not showing. Please help how to solve .

**Comment by iMro0t** [comment]
EPG issue fixed

**Comment by Madmimomana** [comment]
Thankyou dude
