### ISSUE TITLE
Playback error solution

### ISSUE THREAD

**Issue by Madmimomana** [botallen/repository.botallen#298]
**Your Environment**
- Add-on name: [e.g. Jiotv]
- Add-on version: [e.g. 2.0.0]
- Kodi version: [e.g. Kodi 19]
- Operating system version/name: [e.g. Windows 10, LibreElec 9.0, etc...]
- Using from country: [eg. India, USA, etc...]

**Describe the bug**
To get rid of playback error, disable "extra hd channels" in jio add on settings, there's a problem with that, so don't enable it just leave as it is, it will be there below disable welcome popup option,. And really thankyou iMroOt for fixing epg prob, even u did this after that u said it's no longer maintained, thanks a lot dude..

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Additional context**

**Debug log**

The debug log can be found from this link:

**Comment by milindmore22** [comment]
@Madmimomana Thank you for posting the solution,  @iMro0t please continue maintenance of the add-on.
