### ISSUE TITLE
Star Sports channels not working

### ISSUE THREAD

**Issue by NikhilMJain** [botallen/repository.botallen#3]
Hey,

I see that all the HD channels are streaming at 720p ( "_1200.m3u8" links)

Is there any way to select the highest available stream (_4000 for example) ?

Also how can I add star sports select HD 1 and 2?

Thanks

**Comment by botallen** [comment]
Non HLS channels are only available at maximum 720p resolution.

> I see that all the HD channels are streaming at 720p ( "_1200.m3u8" links)
> 
> Is there any way to select the highest available stream (_4000 for example) ?

currently all _1200.m3u8 and _4000.m3u8 are giving 480p ts fragments link. So proxy service is manually replacing that with maximum available fragments (ie, CHANNEL-800_TIMESTAMP.ts to CHANNEL-1200_TIMESTAMP.ts).
And maximum CHANNEL-1200_TIMESTAMP.ts are available CHANNEL-4000_TIMESTAMP.ts doesn't exist. So I'm assuming non-HLS streams are only having maximum 720p resolution.

> Also how can I add star sports select HD 1 and 2?

Star sports channels has SAMPLE-AES encryption and it's not currently supported by inputstream.adaptive [#96](https://github.com/peak3d/inputstream.adaptive/issues/96)

**Comment by NikhilMJain** [comment]
Thank you @botallen 

Awesome job on the plugin BTW. Really appreciate it.
