### ISSUE TITLE
Video quality options

### ISSUE THREAD

**Issue by hsevna** [botallen/repository.botallen#31]
This is a request for enhancement.

Can yu please update the build to watch the videos with multiple video quality options including "Auto", which Hotstar offers. I use VPN to watch and most of the times the videos keep buffering to play the 1080p videos and I couldn't find any options anywhere to change the video quality.

**Comment by botallen** [comment]
> This is a request for enhancement.
> 
> Can yu please update the build to watch the videos with multiple video quality options including "Auto", which Hotstar offers. I use VPN to watch and most of the times the videos keep buffering to play the 1080p videos and I couldn't find any options anywhere to change the video quality.

There is option in player it self. Go to video settings while playing any video and change video channels / quality. It is disabled by default but you can enable it by going to My Add-ons > VideoPlayer Inputstream > Inputstream adaptive > Settings. Change Stream selection Auto to Manual.
