### ISSUE TITLE
Jiotv+ is awesome

### ISSUE THREAD

**Issue by nepalicana** [botallen/repository.botallen#33]
The new addon is awesome. I know since it’s beta version, there are lots of bugs probably. The cinema has a working good, I checked most of the movies in my pc and all were working smooth with toggle available in English and Hindi except one which is awesome. Unfortunately, the live tv section was not working, I guess It is still under construction. Hope to see the final version whenever u feel to release it. Take care dude. And let me know when the time they beta or final is out. I would be more than happy to test it out.

**Comment by nepalicana** [comment]
The JioCinema works without VPN as well, good work.

**Comment by botallen** [comment]
Thanks for your review. Live tv is still in progress as you told. Not sure about final release but it'll be available after i make live tv stable without any lag and with as max quality as possible.

https://github.com/botallen/repository.botallen/issues/32#issuecomment-623251622

Refer to the note in this comment.
