### ISSUE TITLE
Jiotv not working properly,  even unable to stream 5min continues. 

### ISSUE THREAD

**Issue by Suraj824** [botallen/repository.botallen#34]
Dear frd. First of all tysm for your work specially for jiotv+  on,  generally i am using your jiotv add on too much,  but now it is unable to use, even it is not stramin 5min continuely ,so akind request to you to please fix this problem as soon as possible. 

And a kind request to you to please try to add AIRTEL TV.

**Comment by thvardhan** [comment]
I can confirm this issue
