### ISSUE TITLE
Channels are not playing. Confirm same issue on laptop. Env:Ubuntu 20.04

### ISSUE THREAD

**Issue by ANANYANAYAN** [botallen/repository.botallen#340]
**Your Environment**
- JIO TV
-  2.0.0
-  Kodi 19.3, 19.5
- Android, Linux(Ubuntu)
- India

**Describe the bug**
Issue similar to multiple existing issues , channels not playing. 

**Debug log**
23-01-04 00:39:55.576 T:94207   ERROR <general>: CCurlFile::FillBuffer - Failed: HTTP returned error 405
2023-01-04 00:39:55.576 T:94207   ERROR <general>: CCurlFile::Open failed with code 405 for https://sldhnecdnems05.cdnsrv.jio.com/jiotv.live.cdn.jio.com/Jonack/Jonack_800.m3u8:
                                                   
2023-01-04 00:39:55.577 T:94207   ERROR <general>: AddOnLog: inputstream.adaptive: Download failed: https://sldhnecdnems05.cdnsrv.jio.com/jiotv.live.cdn.jio.com/Jonack/Jonack_800.m3u8

Above are some examples of errors from the logs. It seems to me either the cdn's have changed or the authentication has been layered. Attacing full log for reference.
[kodi.log](https://github.com/botallen/repository.botallen/files/10339405/kodi.log)

**Comment by human9839** [comment]
Do you know how to change cdn ?

**Comment by Ayush-045** [comment]
> Do you know how to change cdn ?

What is cdn??

**Comment by sandeep1027** [comment]
issue is not with cdn 405 is method not allowed... i testes all  urls they working fine

**Comment by adityapv** [comment]
Check this one: https://github.com/Geletinousamigo/plugin.video.jiotv

**Comment by ANANYANAYAN** [comment]
Channels are working with https://github.com/Geletinousamigo/plugin.video.jiotv

**Comment by shri1990** [comment]
> Channels are working with https://github.com/Geletinousamigo/plugin.video.jiotv

Can you share the addon zip file for this one?

**Comment by ANANYANAYAN** [comment]
> > Channels are working with  [https://github.com/Geletinousamigo/plugin.video.jiotv ](https://github.com/Geletinousamigo/plugin.video.jiotv)
> 
> Can you share the addon zip file for this one?
[plugin.video.jiotv-1.0.1.zip](https://github.com/botallen/repository.botallen/files/10365805/plugin.video.jiotv-1.0.1.zip)

**Comment by sandeep1027** [comment]
yes channel is working now... i was this close to get this :D
