### ISSUE TITLE
JIO TV, Addon not a single channel is getting play. from mid of december

### ISSUE THREAD

**Issue by Savan353** [botallen/repository.botallen#352]
**Your Environment**
- Add-on name: Jio TV
- Add-on version: [e.g. 2.0.0]
- Kodi version: 19.3
- Operating system version/name: mi box 4K
- Using from country: india

**Describe the bug**
Here is a clear and concise description of what the problem is: once got an update of 19.3, Installed in MI4K box everything was good for few days, after that few channel stop playing, after dec 25,2022 not a single channel is getting played.

**To Reproduce**
4. See an error

**Expected behavior**
Here is a clear and concise description of what was expected to happen: JIO TV channel should be play

**Screenshots**

**Additional context**

**Debug log**

The debug log can be found from this link:
Here is link - https://paste.kodi.tv/ewebaziyah.kodi

**Comment by IAmRohanDsilva** [comment]
Please follow the steps mentioned on https://github.com/botallen/repository.botallen/issues/351 as a workaround.

**Comment by Savan353** [comment]
Thank you for advise it work on me.
