### ISSUE TITLE
Updates your Jiotv in kodi

### ISSUE THREAD

**Issue by Harun7860** [botallen/repository.botallen#359]
Now when I open kodi and play any channel it's saying update your jiotv aap from playstore any solution?

**Comment by zeros13213** [comment]
Same issue from morning

**Comment by navdeepjangra25** [comment]
Yes, please fix this....no channel is playing....on every channel, a video is showing with jio tv update message

**Comment by masternkv** [comment]
Yes same issue coming for me as well please someone resolve this issue

**Comment by navdeepjangra25** [comment]
@iMro0t please look into this issue bro

**Comment by masternkv** [comment]
@iMro0t please look into this bro.... Help us....

**Comment by raosrinivasad** [comment]
Yes . We are also facing the same issue. How to update the jio apk ? Can somebody throw solution?

**Comment by mahanpreetam** [comment]
[
![Screenshot (4)](https://user-images.githubusercontent.com/123226074/213844300-717b6427-77da-4c63-92de-e7a88516aa49.png)
](url)

**Comment by navdeepjangra25** [comment]
@iMro0t please fix this

**Comment by Naruto220891** [comment]
Is this issue now resolved ?

**Comment by mahanpreetam** [comment]
> Is this issue now resolved ?

not yet solved...

**Comment by navdeepjangra25** [comment]
meanwhile use this https://bdixtv24.tk/pd/ to view all channels of jio tv in hd

**Comment by KRISHNAPRIYASHARMA** [comment]
NOT RESOLVED

**Comment by zeros13213** [comment]
Some channels are working now.

**Comment by navdeepjangra25** [comment]
@zeros13213 which channel? No channel is working

**Comment by zeros13213** [comment]
> @zeros13213 which channel? No channel is working
> 

Some sony liv channels like sony six hd, sony max

**Comment by nareshmodi8520** [comment]
https://drive.google.com/drive/folders/1wGMkB5dzQuOm2IbycSjoUa-FAu71QNLE

Use this zip to install (no need to uninstall previous version)

**Comment by raosrinivasad** [comment]
Thanks  .Working now

**Comment by Harun7860** [comment]
> https://drive.google.com/drive/folders/1wGMkB5dzQuOm2IbycSjoUa-FAu71QNLE
> 
> Use this zip to install (no need to uninstall previous version)

Thank you so much
