### ISSUE TITLE
Android TV Leanback App?

### ISSUE THREAD

**Issue by maddy-mad** [botallen/repository.botallen#36]
Hey Buddy,

Any plans for Android TV Leanback App in future? Or any plan to have an interface for live tv links in Android TV native "Live Channel" app with EPG support.

Cheers!!

**Comment by botallen** [comment]
Kodi can't talk directly with android tv. But there are workarounds like you can import m3u playlist in Live channel app. So yes it's possible but it's require little bit of effort from user to import m3u from a particular location.

**Comment by nepalicana** [comment]
> Hey Buddy,
> 
> 
> 
> Any plans for Android TV Leanback App in future? Or any plan to have an interface for live tv links in Android TV native "Live Channel" app with EPG support.
> 
> 
> 
> Cheers!!

@maddy-mad I guess there are plenty to f Android tv apps available for live stream and they include worldwide stations. Try out ola tv, redbox tv, tv tap, swift Streamz. These apps contain almost every station in the world.

**Comment by bhargav1822** [comment]
You create an app that has a cable TV experience that simply generates a
code and connects directly to your server, I use TV Mate apps but some of
the URLs don't work if you have something like that for Jio TV

**Comment by maddy-mad** [comment]
> Kodi can't talk directly with android tv. But there are workarounds like you can import m3u playlist in Live channel app. So yes it's possible but it's require little bit of effort from user to import m3u from a particular location.

Well, I do use my own m3u file to play channels instead of using any app but the problem is Android TV Live Channel app can't be used directly without any app that tells the Live Channel app to use the m3u link. You must have any app to get (invoke) the Live Channel icon on your Android TV. In past, I used an app Called **[CumulusTV](https://github.com/Fleker/CumulusTV)** which does the job with very clean code developed by now Google employee. 

Nowadays I use app called **[OTT Navigator**](https://play.google.com/store/apps/details?id=studio.scillarium.ottnavigator&hl=en) which is awesome but I like to have a clean user interface which btw is default Android TV Live Channel. A perfectly nice and clean look.

**Comment by botallen** [comment]
@maddy-mad  you can also setup IPTV simple kodi add-on ( just one click from settings>setup) and play from kodi itself. you can setup autostart for that from kodi's setting and also setup autostart for kodi in android tv. It's upto you after this you can customize with any kodi skin :beers:

**Comment by Vikassm73** [comment]
I am also using IPTV simple client for live TV, generally news channels. Advantage is, if your TV as well as Kodi Box support HDMI CEC then you can use TV remote to navigate between the channels.
