### ISSUE TITLE
login

### ISSUE THREAD

**Issue by tvpa** [botallen/repository.botallen#39]
![login](https://user-images.githubusercontent.com/53656583/82163060-b9dc3200-9876-11ea-979d-b11544318440.png)

**Comment by Vikassm73** [comment]
You need valid hotstar login to use this app. You have to follow the instructions and proceed

**Comment by tvpa** [comment]
paid one

**Comment by botallen** [comment]
@tvpa  Yes currently you need paid one. But @Vikassm73  is working on `free to watch` content as you seen in hotstar mobile app
