### ISSUE TITLE
Error: CVideoPlayerAudio::Process - stream stalled

### ISSUE THREAD

**Issue by NikhilMJain** [botallen/repository.botallen#4]

**Comment by botallen** [comment]
I am already aware of this behaviour. The reason behind this is some of `.ts` fragments are not exist in server ( 404 not found log ). I thought putting delay between stream will fix that so i put 60sec delay but still no luck.

Also we are updating quality manually by replacing `xx_800-xx.ts` with `xx_1200-xx.ts` So in Jiotv app you'll not get any problem in streaming.

**Comment by NikhilMJain** [comment]
Can we have a switch in the menu that basically tells whether the proxy service should replace the links or not?

Because this is literally unwatchable.

It's better to watch at a slightly lower quality than to not watch at all.

Thoughts?

**Comment by botallen** [comment]
Yes. I am also thinking of that but it'll create lots of conflict because the decryption key is serving by proxy from v1.0.7. So basically i have to add that extra code from old version to choose to not use proxy. So i'm thinking of better solution that fits well in this situation

**Comment by NikhilMJain** [comment]
What if you fetch the low quality .ts link if you get a 404 from the server for the high quality link? That way the stream will not stop and render a low quality stream. Way better than stalling.

**Comment by botallen** [comment]
I thought same but if we change `.ts` from -1200 to -800 in between streaming then it'll still use -1200 key to decrypt and it can not be decrypted by that key so at the end stream will stop playing.

**Comment by NikhilMJain** [comment]
Oh. Then we might need to store the decryption key for both and then use one of them as needed. Do you have a Telegram account where we can discuss if you want?

**Comment by botallen** [comment]
@NikhilMJain I would be happy if you test the new version 1.0.8-3 and let me know if you still facing this issue. Also point if any new issue is you there
