### ISSUE TITLE
bad request 400

### ISSUE THREAD

**Issue by tvpa** [botallen/repository.botallen#45]
![badrequest](https://user-images.githubusercontent.com/53656583/82738835-c34b1b80-9d08-11ea-9601-e3eb13825dce.png)
how do i log in

**Comment by botallen** [comment]
Please describe your issue in details. When you are getting this error ?

**Comment by aayush16sanghavi** [comment]
I cant login to Jio tv id cause i dint remember my password and now in Jio you dont need password they send OTP to Log in so need OTP feature to log in

**Comment by botallen** [comment]
> I cant login to Jio tv id cause i dint remember my password and now in Jio you dont need password they send OTP to Log in so need OTP feature to log in
> 

You can regenerate your password by forgot password option. Please create new issue next time don't interfere with other issue if it is not relevant

**Comment by tvpa** [comment]
![400notfound](https://user-images.githubusercontent.com/53656583/83055761-467ab300-a022-11ea-98c9-dcd16b482deb.png)

when i try to click the link i get this message

**Comment by botallen** [comment]
@tvpa Currently i can't reproduce this. Reinstall add-on and try again. If you are still facing then send me log and reopen this issue.
