### ISSUE TITLE
Cache is not being controlled, on my firestick .cache folder is taking up as huge as 2.5GB

### ISSUE THREAD

**Issue by zengeek** [botallen/repository.botallen#47]
**Your Environment**
- Add-on name: Jiotv
- Add-on version: v2.0.1
- Operating system version/name: Windows 10
- Firestick 2nd gen, Rooted.

**Describe the bug**
The .Cache folder is growing humongous, It is occupying the whole storage space.
/sdcard/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.jiotv/.cache/ 

**To Reproduce**
1. Stream few channels
2. Firestick shows the pop up as running out of space
3. Go to /sdcard/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.jiotv/
4. Check size of .cache folder

**Expected behavior**
It's not being controlled and is growing

**Screenshots**
https://imgur.com/a/txMcsCI

**Additional context**

**Comment by eraianbanc** [comment]
@zengeek  
Workaround to delete cache from Kodi in fire OS in meantime,
1. Turn on both of them at  Settings > Media > General > _Show hidden files and Directories_  and _Allow file renaming and deletion_
2. Add file source in setting > file manager with name jio-tv-cache and select path by selecting browse button. Ensure to select the correct path.
` /sdcard/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.jiotv/`
3. Press options button in Fire TV remote to select all files. 
4. Press options button in remote again to delete all files
