### ISSUE TITLE
cant login in botallen

### ISSUE THREAD

**Issue by aayush16sanghavi** [botallen/repository.botallen#48]
Jio doesn't have new password regeneration or forget password

**Comment by botallen** [comment]
![Screenshot_20200527-220440588](https://user-images.githubusercontent.com/60690413/83047754-70ee5f80-a066-11ea-9d4d-8ff2ed2db964.jpg)

Hope this screenshot will help

**Comment by aayush16sanghavi** [comment]
Thank you!
