### ISSUE TITLE
Can we have Language wise channel selections??? 

### ISSUE THREAD

**Issue by maddy-mad** [botallen/repository.botallen#5]
Love the work you have done... Really appreciate !!

Just a suggestion: can you add language-wise selections of channels? Like If I want to only view Hindi, English and Punjabi Channels and rest can be hidden. Maybe a language selection checkbox.

Thanks
Maddy

**Comment by botallen** [comment]
Will do that soon. I got this idea but forgot to add in my latest release

**Comment by maddy-mad** [comment]
Thanks mate!

**Comment by Chinna-23** [comment]
Any ETA for next release ?

**Comment by botallen** [comment]
> Any ETA for next release ?

It's out now. Check out in repo

**Comment by Chinna-23** [comment]
@botallen : Failed to install add on. after the new release.
