### ISSUE TITLE
Airtel tv!!! Please add irtel tv add on... As soon as possible  a kind request from all of us!!! 

### ISSUE THREAD

**Issue by Suraj824** [botallen/repository.botallen#50]
## Feature request
For Add-on ... [e.g. Jiotv]
I'm submitting a proposal to ...
  - [x] new feature
  - [ ] change an existing feature

#### Development tips
Not obligatory, you can describe how you would develop it, attach links to already prepared code, etc...

**Comment by botallen** [comment]
Duplicate of #40
