### ISSUE TITLE
Airtel tv add on!!!!  A kind request from us please complete it as soon as possible. And tysm for jiotv add on

### ISSUE THREAD

**Issue by Suraj824** [botallen/repository.botallen#51]
## Feature request
For Add-on ... [e.g. Jiotv]
I'm submitting a proposal to ...
  - [ ] new feature
  - [ ] change an existing feature

#### Development tips
Not obligatory, you can describe how you would develop it, attach links to already prepared code, etc...

**Comment by botallen** [comment]
@Suraj824  This is already marked as duplicate of #40 please don't spam by creating same issues again and again
