### ISSUE TITLE
Error during Hotstar Activation

### ISSUE THREAD

**Issue by kedarbhise** [botallen/repository.botallen#52]
@botallen Kudos to you for releasing this addon.

**Your Environment**
- Add-on name: Disney+ Hotstar
- Add-on version: 0.0.26
- Operating system version/name: OSMC 2020.03-1 on Raspberry Pi 3B+, with Kodi 18.6

**Describe the bug**
When trying to activate the Disney+ Hotstar addon using [Hotstar Activation Screen](https://hotstar.com/in/activate), we get the following error in the top right corner of the screen:
`KeyError: u'isGuest'`

After this error, the addon allows me to browse and play all content on Disney+ Hotstar including Premium content. However, progress is not saved and thus other devices are not aware of content watched on this device.

**To Reproduce**

1. Go to 'Settings' -> 'Áddon Browser' -> 'Video Addons' -> 'Disney+ Hotstar'
2. On the addon information page, Click on 'Configure' -> 'Login'
3. The Login screen shows a four character activation code.
4. Visit https://hotstar.com/in/activate via any browser. If required, login using your credentials.
5. Enter the four character activation code from the addon on TV screen.
6. Activation page on browser shows 'Activation Successful'
7. Addon shows error: `KeyError: u'isGuest'` shows up on the top right corner of TV screen.
8. I can browse and view all content including Premium content, but progress is not saved.

**Expected behavior**
1. Activation should happen with appropriate success message.
2. After watching any content on Disney+ Hotstar via this addon, progress should be saved.

**Screenshots**

**Additional context**

**Debug log**

Please let me know if you need more information.

**Comment by kedarbhise** [comment]
@botallen Thanks for closing this bug.

Is the fix for this part of the latest commit? Should I update the add-on on my side?

**Comment by botallen** [comment]
> @botallen Thanks for closing this bug.
> 
> Is the fix for this part of the latest commit? Should I update the add-on on my side?

Yes it's fixed now except watch progress. Watch progress sync is not easy to implement so i have to dig little bit more (how netflix addon implemented it)

**Comment by kedarbhise** [comment]
@botallen  Thank you.
I am trying to update, but the botallen repository shows version 0.0.26, which is the previous version.
The latest version `0.0.27` is not available via https://kodi.botallen.com
Is there another method to update to `0.0.27`?

> Yes it's fixed now except watch progress. Watch progress sync is not easy to implement so i have to dig little bit more (how netflix addon implemented it)

Thanks for the comment. I am happy to wait for progress sync.

**Comment by botallen** [comment]
> @botallen Thank you.
> I am trying to update, but the botallen repository shows version 0.0.26, which is the previous version.
> The latest version `0.0.27` is not available via https://kodi.botallen.com
> Is there another method to update to `0.0.27`?
> 
> > Yes it's fixed now except watch progress. Watch progress sync is not easy to implement so i have to dig little bit more (how netflix addon implemented it)
> 
> Thanks for the comment. I am happy to wait for progress sync.

Try restarting kodi or Go to Repository and open context menu and select check for update. you'll get v0.0.27

**Comment by kedarbhise** [comment]
> Try restarting kodi or Go to Repository and open context menu and select check for update. you'll get v0.0.27

Thanks for the tip. The Context Menu -> Check for Updates allowed me to get 0.0.27. Will try out and report back.

Also, in the dependencies section, one particular dependency `script.module.win_inet_pton` is always shown as "Not available". Let me know if you prefer a separate bug for this.

**Comment by kedarbhise** [comment]
@botallen Good News!

1. At the activation screen, I no longer get the error message: `KeyError: u'isGuest'`. So activation is _successful_.
2. For some video titles, subtitles are working. Not sure why they are not working across the board.

Let me know how I can help further.
