### ISSUE TITLE
Some channels are not working 

### ISSUE THREAD

**Issue by keerthivasan19** [botallen/repository.botallen#56]
Some of the Tamil channels didn’t work if I click the channel icon it shows the loading cursor and doesn’t open up. If I delete and reinstall the addon it works for some time and again it stops working(some channels).

**Comment by gpkumaran** [comment]
Yes. I will make a list of all the channels showing such behaviour. From My memory, pudhiya thalaimurai and channel news asia doesnt play

**Comment by keerthivasan19** [comment]
Yeah you are right what should I do now any method to overcome that ??

**Comment by keerthivasan19** [comment]
> Yes. I will make a list of all the channels showing such behaviour. From My memory, pudhiya thalaimurai and channel news asia doesnt play


Yeah you are right what should I do now any method to overcome that ??

**Comment by maanich** [comment]
do we need  indian ip to see the jio streams? or just need mob and email associated with jio
what about airtel and tatsky

**Comment by keerthivasan19** [comment]
> do we need  indian ip to see the jio streams? or just need mob and email associated with jio
> 
> what about airtel and tatsky

Yes, you need Indian IP or else use VPN and switch to India

**Comment by Satish1972** [comment]
Hi,,Zee TV kannada and BTV not working

**Comment by botallen** [comment]
#58 #59

**Comment by Chinna-23** [comment]
Hi team, Any ETA for this fix. Tamil channels are not working. :(

**Comment by anishsane** [comment]
I also face same issue for some channels. I noticed that only some particular channels show this issue.
Also, the issue is sporadic. I.e., the channels sometimes start working after some time (some time since kodi startup).

If you want, here is the snippet from kodi.log:

    T:1295737040   ERROR: 127.0.0.1 - - [25/Jul/2020 13:26:55] Request timed out: timeout('timed out',)
    T:2973359200  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.jiotv/resources/lib/main/play/?_pickle_=80027d71005802000000647471017d710228580500000070726f746f71035803000000686c73710458040000007055726c7105583b000000687474703a2f2f3132372e302e302e313a34383939362f706c61792f4142505f4d616a68612f6d61737465722e6d3375383f6d6178713d31323030710658050000006c6162656c71075809000000414250204d616a686171085805000000634c6f676f7109580d0000004142505f4d616a68612e706e67710a580400000063496d67710b585100000068747470733a2f2f6a696f696d616765732e63646e2e6a696f2e636f6d2f696d616765737075626c69632f34342f34342f4142504d616a68615f313537343636393933333939335f70726f6d6f2e6a7067710c75732e
    T:1708298448   ERROR: 127.0.0.1 - - [25/Jul/2020 13:26:57] "HEAD /play/ABP_Majha/master.m3u8?maxq=1200 HTTP/1.1" 200 -
    T:1379918032  NOTICE: Creating InputStream
    T:1177723088   ERROR: GetDirectory - Error getting -
    T:1708298448   ERROR: 127.0.0.1 - - [25/Jul/2020 13:26:59] "GET /play/ABP_Majha/master.m3u8?maxq=1200 HTTP/1.1" 200 -
    T:1379918032  NOTICE: Creating Demuxer
    T:1379918032  NOTICE: Opening stream: 1001 source: 256
    T:1708298448   ERROR: 127.0.0.1 - - [25/Jul/2020 13:26:59] "GET /play/ABP_Majha/ABP_Majha_JSRV6_1200.m3u8?maxq=1200 HTTP/1.1" 200 -
    T:1708298448   ERROR: 127.0.0.1 - - [25/Jul/2020 13:27:01] "GET /play/ABP_Majha/ABP_Majha_1200-1595663792000.ts HTTP/1.1" 200 -
    T:1363132624   ERROR: 127.0.0.1 - - [25/Jul/2020 13:27:01] code 404, message Not Found
    T:1363132624   ERROR: 127.0.0.1 - - [25/Jul/2020 13:27:01] "GET /play/ABP_Majha/ABP_Majha_1200-1595663328000.key HTTP/1.1" 404 -
    T:1295737040   ERROR: CCurlFile::Open failed with code 404 for http://127.0.0.1:48996/play/ABP_Majha/ABP_Majha_1200-1595663328000.key:
    T:1363132624  NOTICE: [JioTV] [Errno 104] Connection reset by peer
    T:1363132624   ERROR: 127.0.0.1 - - [25/Jul/2020 13:27:01] code 500, message Internal Server Error
    T:1363132624   ERROR: 127.0.0.1 - - [25/Jul/2020 13:27:01] "GET /play/ABP_Majha/ABP_Majha_1200-1595663328000.key HTTP/1.1" 500 -
    T:1295737040   ERROR: AddOnLog: InputStream Adaptive: Cannot download http://127.0.0.1:48996/play/ABP_Majha/ABP_Majha_1200-1595663328000.key
    T:1363132624   ERROR: Traceback (most recent call last):
    T:1363132624   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    T:1363132624   ERROR:     self.finish_request(request, client_address)
    T:1363132624   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    T:1363132624   ERROR:     self.RequestHandlerClass(request, client_address, self)
    T:1363132624   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
    T:1363132624   ERROR:     self.finish()
    T:1363132624   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
    T:1363132624   ERROR:     self.wfile.close()
    T:1363132624   ERROR:   File "/usr/lib/python2.7/socket.py", line 283, in close
    T:1363132624   ERROR:     self.flush()
    T:1363132624   ERROR:   File "/usr/lib/python2.7/socket.py", line 307, in flush
    T:1363132624   ERROR:     self._sock.sendall(view[write_offset:write_offset+buffer_size])


Some 5 minutes ago, I was facing the same problem and same error log for "Zee 24 taas" channel. And suddenly, it started working after I clicked on the channel few times (in order to see the logs).

**Comment by geethatamilselvan** [comment]
All the tamil channels are not working in jio tv addons. please do something.

**Comment by ManoharOfficial** [comment]
> All the tamil channels are not working in jio tv addons. please do something.

I also observed the same thing with Telugu channels too. Some that actually previously worked, are all of a sudden now not working

**Comment by sudesna401** [comment]
zee channels, aajtak, times now, ndtv  maximum channels not working now. @botallen

**Comment by anishsane** [comment]
>  botallen added this to **Done** in [Botallen Repo Progress](https://github.com/botallen/repository.botallen/projects/1#card-42664550) on Jul 28

So, is it fixed or triaged?
Is there a test build that we can beta test?
