### ISSUE TITLE
Facing error while trying to play movies and series through Jiotv +

### ISSUE THREAD

**Issue by nepalicana** [botallen/repository.botallen#57]
**Your Environment**
- Add-on name: jiotv +
- Add-on version: 0.0.21
- Operating system version/name: Windows 10, iOS 

**Describe the bug**
Get http client error 419 while trying to play series and movies from the addon but live tv works fine 

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/62384935/85186423-a3335b80-b2b8-11ea-8167-84b7201c5f6b.jpeg)

**Additional context**

**Debug log**

https://paste.kodi.tv/gedayihiwu

**Comment by botallen** [comment]
It's know issue. Because of jiotv+ login token expired you are facing this issue. As of now jiotv has no official refresh token endpoint so I'm thinking to add two options weather to remember username and password and store them or asking again from user. I would like if you'll five some feedback about it

**Comment by botallen** [comment]
Workaround : try reinstall with clearing userdata

**Comment by nepalicana** [comment]
Ya signing out then re-signin helps

Sent from my iPhone

On Jun 20, 2020, at 09:28, botallen <notifications@github.com> wrote:

﻿

It's know issue. Because of jiotv+ login token expired you are facing this issue. As of now jiotv has no official refresh token endpoint so I'm thinking to add two options weather to remember username and password and store them or asking again from user. I would like if you'll five some feedback about it
