### ISSUE TITLE
Channels are not working

### ISSUE THREAD

**Issue by ManikandanGuru** [botallen/repository.botallen#59]
Except for Star channels, most of the channels I selected didn't work at all. Tried Tamil channels none of it worked. Channels other than Star Sports are not working. Reinstalled repo, updated add-ons. Nothing helped. Is there any way to fix this please?

**Comment by botallen** [comment]
@ManikandanGuru  please follow issue template so i can understand in details about your issue. Add log file and try relogin.

**Comment by botallen** [comment]
Duplicate of #56
