### ISSUE TITLE
Catchup and some channels not working

### ISSUE THREAD

**Issue by TheVaibhavSinghal** [botallen/repository.botallen#60]
**Your Environment**
- Add-on name: Jiotv 
- Operating system version/name: Android TV (Pie)

**Describe the bug**
Some channels such as Star sports, Sony SAB(SD), Sony Pal are not working in PVR IPTV Simple Client. Also I am unable to view catchup TV in PVR IPTV Simple Client.

**Comment by Vatsal77-web** [comment]
On kodi os too

**Comment by botallen** [comment]
Catchup play from PVR add-on does not supports in kodi 18. This is implemented in kodi 19.
