### ISSUE TITLE
Tivimate Support

### ISSUE THREAD

**Issue by jaspreet997** [botallen/repository.botallen#62]
Can you provide a way to generate a m3u8 which is compatible with Tivimate? The generation can still be done from inside Kodi and a path can be given in settings for the generated file. Kodi is great but the TV ui is sluggish compared to Tivimate. 

Also suggest any workarounds or hacks already possible

**Comment by iMro0t** [comment]
It's on way. Try beta version and let me know if you are facing any problem with tivimate. [#apply-for-beta](https://botallen.com/discord)
