### ISSUE TITLE
Sun Network channels are not working

### ISSUE THREAD

**Issue by karthi5040** [botallen/repository.botallen#63]
All tamil channels are working good. But few weeks ago. Sun Network channels are not working.

**Comment by echakkara** [comment]
Sun network channels are not being available from Jio TV itself and can be marked for closure

**Comment by karthi5040** [comment]
I am going write SunNeXt application in python 😂 
Thanks for the immediate response.

**Comment by botallen** [comment]
@karthi5040 better create kodi addon if you are planning to do it in python. Let me know if you need any help 🍻

**Comment by keerthivasan19** [comment]
> I am going write SunNeXt application in python 😂 
> 
> Thanks for the immediate response. 

For that create airtel Xstream app bro It has all the sun network channels and it's still working.
