### ISSUE TITLE
Lionsgate content not working

### ISSUE THREAD

**Issue by mananhiteshkataria** [botallen/repository.botallen#64]
I am a jio fiber gold subscriber if you need any help making the jio TV + app work from my side please let me know there are some other people I know from a telegram group as well who would love to help.

**Comment by iMro0t** [comment]
Thanks for that. I will let you know if i want any help. Join our discord channel [here](http://botallen.com/discord). Also tell those telegram folks to join as well. We had lots of discussion going on there about add-ons. 

Can you elaborate your issue with more details ?

**Comment by iMro0t** [comment]
This add-on is deprecated.
