### ISSUE TITLE
Most Channels do not work

### ISSUE THREAD

**Issue by grizzy255** [botallen/repository.botallen#71]
**Your Environment**
- JioTv 2.0.12
- Ubuntu 20.04.1 LTS
- Kodi - 18.8.0
- InputStream Adaptive - 2.4.5

**Describe the bug**
Most Channels do not work

The debug log can be found from this link: https://termbin.com/r8wk
17:55:35 > Channel NOT working
17:55:55 > Working channel

**Comment by botallen** [comment]
Token expired. Try with relogin

**Comment by grizzy255** [comment]
Thank you for the response. Its not the login - I cleared the cache, logged out and then opened a channel.Prompted me for user/pass. I entered and again the same 403 errors. Any other ideas ?
