### ISSUE TITLE
How to play jioTv channels. On iptv outside of kodi with userid and password

### ISSUE THREAD

**Issue by dma143** [botallen/repository.botallen#73]
## Feature request
For Add-on ... [e.g. Jiotv]
I'm submitting a proposal to ...
  - [ ] new feature
  - [ ] change an existing feature

#### Development tips
Not obligatory, you can describe how you would develop it, attach links to already prepared code, etc...

**Comment by botallen** [comment]
As of now in Jiotv 2.0.13 you can play channels in external players like tivimate
