### ISSUE TITLE
Maximum JIOTV channels not working

### ISSUE THREAD

**Issue by sudesna401** [botallen/repository.botallen#75]
**Your Environment**
- Add-on name: [e.g. Jiotv]
- Add-on version: [e.g. 2.0.0]
- Operating system version/name: [LibreElec 9.2.4 & linux mint 20]

**Describe the bug**
maximum channels not working of jio tv source like news music channels. Sony liv & star channels working but jiotv maximum channels not working.

*

**Comment by raghav998** [comment]
Same here bud, Only Star channels seems to be working

**Comment by anshuman852** [comment]
Ye same here

**Comment by stephenvaz03** [comment]
> Ye same here

Almost all channels are working fine, could you check if the Jio Account you're using is working in the official jio tv mobile app. It is possible that your jio id itself is banned (happened to me a month ago). In case of a ban on your ID just use another Jio ID

**Comment by raghav998** [comment]
> > Ye same here
> 
> Almost all channels are working fine, could you check if the Jio Account you're using is working in the official jio tv mobile app. It is possible that your jio id itself is banned (happened to me a month ago). In case of a ban on your ID just use another Jio ID

The issue was in addon btw. It also didn't worked for me. **Join discord and download beta.** Beta version working fine without any issue for me

**Comment by anshuman852** [comment]
> > > Ye same here
> > 
> > Almost all channels are working fine, could you check if the Jio Account you're using is working in the official jio tv mobile app. It is possible that your jio id itself is banned (happened to me a month ago). In case of a ban on your ID just use another Jio ID
> 
> The issue was in addon btw. It also didn't worked for me. **Join discord and download beta.** Beta version working fine without any issue for me

Still some are not working like history tv 18 hindi

**Comment by lal-abhinav** [comment]
> > > Ye same here
> > 
> > 
> > Almost all channels are working fine, could you check if the Jio Account you're using is working in the official jio tv mobile app. It is possible that your jio id itself is banned (happened to me a month ago). In case of a ban on your ID just use another Jio ID
> 
> The issue was in addon btw. It also didn't worked for me. **Join discord and download beta.** Beta version working fine without any issue for me

I am new to GitHub, kindly guide me, how to **Join discord and download beta.** and get the Beta version.

**Comment by stephenvaz03** [comment]
> > > > Ye same here
> > > 
> > > 
> > > Almost all channels are working fine, could you check if the Jio Account you're using is working in the official jio tv mobile app. It is possible that your jio id itself is banned (happened to me a month ago). In case of a ban on your ID just use another Jio ID
> > 
> > 
> > The issue was in addon btw. It also didn't worked for me. **Join discord and download beta.** Beta version working fine without any issue for me
> 
> I am new to GitHub, kindly guide me, how to **Join discord and download beta.** and get the Beta version.
Discord Invite: https://discord.com/invite/bUDYtFP , most of the instructions are already available, if you stilll face any isssue installing beta versions you can always ping the beta-chat channel on discord
