### ISSUE TITLE
add select server option for jiotv

### ISSUE THREAD

**Issue by sudesna401** [botallen/repository.botallen#76]
## Feature request
For Add-on ... [e.g. Jiotv]
I'm submitting a proposal to ...
  - [ ] new feature

please add select server feature in jiotv asddon. like delhi, mumbai,kolkata etc server can be selected manually so that we can chose opur nearest server to get less ping & optimized tv experience.

**Comment by botallen** [comment]
Jio's cdn is already redirecting to appropriate region server
