### ISSUE TITLE
Sonyliv & Hotstar

### ISSUE THREAD

**Issue by Taburientelp1** [botallen/repository.botallen#80]
Hi there, 

First of all thanks  for the amazing work that you guys are doing its really appreciated,  would like to ask is it possible to have a sonyliv & hotstar  addon  that works  out of india...? at least the shows  ?  the zee5 add on  works perfect and its amazing

Thanks a lot  once again, 

and keep up tha amazing work

**Comment by ForceGT** [comment]
I guess this seems probably impossible because the cdn of SonyLIV and Tata Sky are georestricted
@iMro0t  could try something with vpn or @Taburientelp1 probably you yourself can work with Indian VPN

**Comment by iMro0t** [comment]
This is not possible due to geo-restriction. You can use "some kind" of services to bypass that.
