### ISSUE TITLE
Hotstar: Sort TV shows in descending order of episodes

### ISSUE THREAD

**Issue by satyadeepk** [botallen/repository.botallen#81]
## Feature request
For Add-on: Hotstar
I'm submitting a proposal to ...
  - [ ] new feature
  - [x] change an existing feature

#### Is your feature request related to a problem? Please describe.
To watch the latest episodes of a show on Star TV for example, we need to go page by page until the last page to reach the most recent episode. 
If a show has 500+ episodes, it takes 25 pages to reach the last page.

#### Describe the solution you'd like
It will be great if the TV shows are sorted in descending order of episodes by date. It seems to be possible on Hotstar Web and Android apps.

#### Development tips
I have a background in Python, if you can guide the location of the APIs and tell if sorting option is possible in the Hotstar API, I can give it a shot.

**Comment by iMro0t** [comment]
Added support to sort episodes in descending and showing all episodes at once without pagination as well in version 1.0.0
