### ISSUE TITLE
Star channels are not working

### ISSUE THREAD

**Issue by devil47sid** [botallen/repository.botallen#85]
Thanks for the wonderful you did and I hope you continue to support this. I see the list have mentioned Star Plus and other channels status as working but unfortunately I unable to play anyone of them. Can you please check for the issue?

**Comment by test2a** [comment]
same here but for me sports channels are not working.

**Comment by pratulk09** [comment]
This is a constant problem and I have not seen any star channels working, maybe there is issue with the encryption/decryption.

**Comment by uzairmukadam** [comment]
In android of you select any of the start sports channel, it launches that channel in Hotstar. Maybe this is what's causing it to not play.

**Comment by iMro0t** [comment]
Added support in latest version 2.1.0
