### ISSUE TITLE
IPL Highlights in English

### ISSUE THREAD

**Issue by guy99au** [botallen/repository.botallen#86]
Great addon for watching IPL highlights but are they available in English? The Hotstar website has the option to select language in the player.

**Comment by scamper07** [comment]
+1

**Comment by iMro0t** [comment]
@guy99au @scamper07 in case you didn't notice i added language selection option in context menu in that commit. 
It'll look something like this
![Screenshot from 2020-10-02 20-42-34](https://user-images.githubusercontent.com/25949138/94939493-dc9e7880-04ef-11eb-92dc-1eb6b8edd50b.png)

**Comment by scamper07** [comment]
Thank you :+1:
