### ISSUE TITLE
play() got an unexpected argument dt or Unable to concatenate str with Nonetype object

### ISSUE THREAD

**Issue by SurajGuptaRavi** [botallen/repository.botallen#91]
- Add-on name: JioTv+
- Add-on version: latest version
- Operating system version/name: Android tv / Android mobile and Windows

whenever i try to play any channel in JioTv+ it encountered  error sometimes this  "play() got an unexpected argument dt" or Unable to concatenate str with Nonetype object

2. Click on '....':any channel to play in JioTv+

**Comment by iMro0t** [comment]
This add-on is deprecated.
