### ISSUE TITLE
Background service crash

### ISSUE THREAD

**Issue by bowss** [botallen/repository.botallen#92]
**Your Environment**
- Add-on name:  Jiotv
- Add-on version: 2.0.0
- Operating system version/name: Android TV 5.1

**Comment by parthdevloper** [comment]
+1

**Comment by parthdevloper** [comment]
I GOT the solution ....

Download this one as seen in image
![image](https://user-images.githubusercontent.com/58413215/98711096-92d86600-23aa-11eb-8a77-7b8b022c0340.png)


Now Step 1 :  Remove the old Jiotv (ie. latest one ) that you installed in KODI app.
By navigating to ADD-ON > uninstall

Step 2 :  Download  from here > AND UPLOAD to your Android TV or Fire TV STICK
https://github.com/botallen/repository.botallen/blob/master/plugin.video.jiotv/plugin.video.jiotv-2.0.0.zip

Step 3 : Login by Moving to Config  > SEE IMAGE
![image](https://user-images.githubusercontent.com/58413215/98711775-6ffa8180-23ab-11eb-953a-54e44e466517.png)

Now `Restart` your tv/fire tv To work...
Now, You won't get error `jio tv service crashed, restarting`

Hope this helped...

**Comment by iMro0t** [comment]
Marking this as closed. This is fixed in the new Jiotv version 2.0.14
