### ISSUE TITLE
Not Able to Login in JioTv app

### ISSUE THREAD

**Issue by anhiahekrxz** [botallen/repository.botallen#93]
**Your Environment**
- Add-on version: [Jiotv 2.0.13]
- Add-on version: [JioTv+ 0.0.22]

**Describe the bug**
Not able to Login for Jio apps.

**To Reproduce**
1. Install Add On.
2. Video Add On - JioTv / JioTv+
3. Select any channel which prompts login
4. Enter mobile number and wait for OTP

**Expected behavior**
OTP on given Jio number shall received.

**Debug log**

The debug log can be found from this link:

**Comment by iMro0t** [comment]
There is no option for OTP. You have to login with your email id and password as it is clearly asking for.
