### ISSUE TITLE
not able to install

### ISSUE THREAD

**Issue by prabalhclite** [botallen/repository.botallen#95]
**Your Environment**
- Add-on name: [e.g. Jiotv]
- Add-on version: [e.g. 2.0.0]
- Operating system version/name: Android 4.4.2

While trying to install from repository in kodi,no zip file is showing.

in MYGICA
while trying to install it showing installation failed

**Comment by iMro0t** [comment]
Follow this guide. [https://botallen.com/blog/jiotv-kodi-add-on](https://botallen.com/blog/jiotv-kodi-add-on)

Feel free to reopen if you are still having a problem with the installation

**Comment by chiragvadhavana** [comment]
it's not working on android kitkat, is there any way to run jiotv using botallen? ( in android kitkat which only supports till kodi 16)

**Comment by iMro0t** [comment]
> it's not working on android kitkat, is there any way to run jiotv using botallen? ( in android kitkat which only supports till kodi 16)

@chiragvadhavana currently only Kodi 19 is supported.
