### ISSUE TITLE
Please add Support for Kodi Matrix

### ISSUE THREAD

**Issue by ashokmanker** [botallen/repository.botallen#99]
## Feature request
For Add-on ... [e.g. Jiotv]
I'm submitting a proposal to ...
  - [ ] new feature
  - [x] change an existing feature

#### Is your feature request related to a problem? Please describe.
Plugin is not installing in Kodi Matrix 

#### Describe the solution you'd like
Dependency issue 

#### Describe alternatives you've considered
Tried installing separate zip file but plugin disbled

#### Additional context
Since as you have mentioned catchup is supported in Kodi Matrix but plugin is not working in Matrix

**Comment by porusbaker** [comment]
Plugin is broken in Kodi Matrix
